export const page = {
  title: "Reference Checker",
  summary: "Reviews APA 7 reference lists for structural issues, missing metadata, duplicates, ordering and items that need manual review.",
  metaDescription: "Check APA 7 reference lists for missing metadata, structural problems, duplicates, ordering issues and items that need manual review.",
  intro: "Paste a reference list to inspect what ResearchKit can determine. The checker preserves your text, explains uncertainty and never silently rewrites metadata.",
  noScript: "The Reference Checker needs JavaScript to inspect the reference list. Turn on JavaScript to use it.",
  howHeading: "How the checker works",
  how: [
    "Paste one or more references, using a blank line between entries when possible.",
    "ResearchKit identifies supported journal article, book and web page structures where it can.",
    "Review each detected issue against the original source. No detected issue does not mean a reference is verified.",
  ],
  limitsHeading: "What this checker cannot determine",
  limits: [
    "It does not resolve DOIs, fetch publisher metadata or test whether URLs are live.",
    "It does not correct, reorder, delete or merge your reference text.",
    "It does not check every APA exception or determine whether a source is credible.",
    "It does not scan an essay for citations or prove that every reference was used.",
  ],
  privacyHeading: "Privacy",
  privacy: "Checking happens in your browser. Your reference text is not sent to ResearchKit, stored in the workspace or placed in the URL.",
  inputHeading: "Paste your reference list",
  inputLabel: "APA 7 reference list",
  inputHint: "Use a blank line between references. Long references may wrap across lines.",
  placeholder: "Smith, J. (2024). Article title. Journal Name, 10(2), 10–20. https://doi.org/10.1234/example\n\nKahneman, D. (2011). Thinking, fast and slow. Publisher.",
  check: "Check references",
  clear: "Clear",
  empty: "Paste your APA 7 reference list above to check common structural, metadata, ordering and formatting issues.",
  resultsHeading: "Review summary",
  referenceCount: (count: number) => `${count} ${count === 1 ? "reference" : "references"} reviewed`,
  issueCount: (count: number) => `${count} ${count === 1 ? "reference" : "references"} with detected issues`,
  duplicateCount: (count: number) => `${count} potential duplicate ${count === 1 ? "entry" : "entries"}`,
  orderingCount: (count: number) => `${count} ${count === 1 ? "ordering issue" : "ordering issues"}`,
  manualCount: (count: number) => `${count} manual-review ${count === 1 ? "item" : "items"}`,
  noDetected: "No implemented checks found an issue in this reference.",
  reference: (index: number) => `Reference ${index}`,
  original: "Original text",
  sourceType: "Detected source type",
  confidence: "Parse confidence",
  high: "High",
  partial: "Partial",
  unable: "Unable to determine",
  issues: "Issues to review",
  action: "Suggested action",
  copyReference: "reference text",
  copySummary: "review summary",
  learnLink: "Learn how APA 7 references work",
  builderLink: "Build an APA reference",
} as const;

export const severityLabel = {
  error: "Error",
  warning: "Warning",
  information: "Information",
} as const;
