/** All wording for the Questionnaire Builder. Academic content lives in the knowledge layer. */

export const page = {
  title: "Questionnaire Builder",
  /** One sentence, for listings such as the tools index. */
  summary: "Assembles a structured questionnaire from your variables and indicators, explains where every question comes from, and exports it to Word, PDF and Markdown.",
  metaDescription:
    "Build a questionnaire from your research variables and indicators: standard sections, sixteen question types, Likert and other rating scales, checks against your hypotheses and objectives, and Word, PDF and Markdown export. You write every question.",
  intro:
    "Enter your project, and the builder sets out a questionnaire: the standard sections, and a question for every indicator of every variable, each traced back to your research question, objectives and hypotheses. It never writes question wording for you. Edit everything, preview it on screen and on paper, and export it.",
  noScript:
    "The Questionnaire Builder responds to your project and edits, which needs JavaScript. Turn on JavaScript to use it. The guide to question types and scales below works without it.",
  howHeading: "How the builder works",
  limitsHeading: "What this tool can't do",
  reviewHeading: "Awaiting review",
  privacyHeading: "Privacy",
  privacy: "Everything stays in your browser. Nothing is sent anywhere or saved, and it is cleared when you leave the page. Word and PDF files are made in your browser too.",
} as const;

export const how: readonly string[] = [
  "The builder reads your project draft: research question, aim, objectives, variables and their indicators, hypotheses, conceptual framework and who will answer. Enter them in the first step; later versions will bring them across from the other research tools.",
  "Every measuring question comes from a chain: variable, indicator, operational definition, question. Your own draft items become questions; every other indicator gets a placeholder naming what to ask about.",
  "Question types start from each indicator's measurement level, and every choice can be changed. Checks look for gaps against your variables, hypotheses and objectives, and never score your questionnaire.",
  "Previews show the questionnaire on screen, at phone width, and as printed pages that match the PDF. Word lays out its own pages.",
  "The builder writes only the questionnaire section of your project draft, which later tools, such as a codebook or pilot testing planner, will read.",
];

export const steps = {
  project: "Project details",
  projectIntro: "Enter what you already know. The builder never invents variables, indicators or wording.",
  example: "Load an example project",
  exampleLoaded: "Example project loaded and questionnaire built. It is fictional, for trying the builder.",
  topic: "Topic",
  topicHint: "Used as the questionnaire's title until you change it.",
  aim: "Research aim",
  question: "Research question",
  objectives: "Research objectives",
  perLine: "One per line.",
  variablesHint: "One variable per line. Put its indicators after a colon, separated by semicolons, such as “sleep quality: time to fall asleep; feeling rested”.",
  independent: "Independent variables",
  dependent: "Dependent variables",
  control: "Control variables",
  controlHint: "Asked about in the demographic section. One per line, with indicators as above.",
  levelsLegend: "How each variable is measured",
  levelsHint: "The measurement level suggests each question's type. Leave it unset if you don't know yet.",
  levelLabel: (name: string) => `${name}: measured as`,
  notSet: "Not set",
  population: "Who will answer",
  populationHint: "Your target population, from your sampling plan.",
  hypothesesLegend: "Hypotheses",
  hypothesesHint: "Until the tools share a saved project, the builder can draft hypotheses from your variables with the Hypothesis Builder's rules.",
  withHypotheses: "Draft hypotheses from these variables",
  withoutHypotheses: "No hypotheses",
  build: "Build the questionnaire",
  buildIntro: "Sets out the standard sections, a consent question, and one question for every indicator of every variable.",
  buildButton: "Build from my project",
  rebuildButton: "Start again from my project",
  rebuildWarning: "This replaces the questionnaire below, including your edits. Export it first if you want to keep it.",
  rebuildConfirm: "Replace my questionnaire",
  rebuildCancel: "Keep my questionnaire",
  addMissing: "Add questions for anything unmeasured",
  notBuilt: "Build the questionnaire first.",
  structure: "Sections",
  structureIntro: "Rename, reorder, remove or add sections. Moving a section moves its questions; removing it removes them.",
  title: "Questionnaire title",
  sectionTitle: (position: number) => `Title of section ${position}`,
  sectionText: "Text shown before the questions",
  sectionTextHint: (placeholder: string | null) => (placeholder ? `Until you write it, the questionnaire shows: ${placeholder}` : "Optional."),
  guidance: "From your project",
  titleRequired: "A section needs a title.",
  moveUp: "Move up",
  moveDown: "Move down",
  remove: "Remove",
  removeSection: (title: string, questions: number) => `Remove section “${title}”${questions > 0 ? ` and its ${questions} ${questions === 1 ? "question" : "questions"}` : ""}`,
  newSection: "New section title",
  addSection: "Add section",
  questions: "Questions",
  questionsIntro: "Every question you see comes from your project. Open “Edit” to write its wording and change anything else, and “Why this question exists” to trace it back.",
  sectionQuestionsCount: (count: number) => (count === 0 ? "No questions yet." : `${count} ${count === 1 ? "question" : "questions"}.`),
  questionHeading: (number: string) => `Question ${number}`,
  required: "Required",
  optional: "Optional",
  linkedTo: (name: string) => `Measures ${name}`,
  notLinked: "Not linked to a variable",
  addQuestion: (section: string) => `Add a question to ${section}`,
  edit: (number: string) => `Edit question ${number}`,
  why: (number: string) => `Why question ${number} exists`,
  wording: "Question wording",
  wordingHint: "In your own words. Until you write it, the questionnaire shows a placeholder.",
  type: "Question type",
  section: "Section",
  variable: "Variable it measures",
  noVariable: "None",
  indicator: "Indicator it measures",
  noIndicator: "None chosen",
  requiredLegend: "Answer",
  help: "Help text for respondents",
  notes: "Your notes",
  notesHint: "Never shown to respondents.",
  options: "Answer options",
  optionsHint: "One per line.",
  rows: "Statements",
  rowsHint: "One per line. Each is rated on the scale below.",
  duplicate: "Duplicate",
  delete: "Delete",
  deleteQuestion: (number: string) => `Delete question ${number}`,
  duplicateQuestion: (number: string) => `Duplicate question ${number}`,
  moveQuestionUp: (number: string) => `Move question ${number} up`,
  moveQuestionDown: (number: string) => `Move question ${number} down`,
  scale: "Scale",
  scalePreset: "Scale",
  scaleLabels: "Labels",
  scaleLabelsHint: "One per point, in order. Changing them makes the scale custom.",
  scaleAnchors: "Words for the two ends",
  lowAnchor: "First end",
  highAnchor: "Last end",
  scaleStart: "Lowest point is recorded as",
  scaleDirection: "Numbers run",
  ascending: "Up from the first label",
  descending: "Down from the first label",
  reverse: "Reverse-scored",
  reverseHint: "For items worded the opposite way to the others.",
  yes: "Yes",
  no: "No",
  coding: "Coding",
  chain: "From variable to question",
  researchQuestion: "Research question",
  objectivesHeading: "Objectives it supports",
  hypothesesHeading: "Hypotheses it supports",
  frameworkHeading: "Conceptual framework",
  populationHeading: "Who answers",
  none: "None named.",
  checks: "Checks",
  checksIntro: "What the builder can check: links, coverage and structure. Wording quality needs piloting and review.",
  counts: "What the questionnaire contains",
  countSections: "Sections",
  countQuestions: "Questions",
  countRequired: "Required",
  countUnwritten: "Still to be worded",
  byType: "By type",
  byVariable: "By variable",
  preview: "Preview",
  previewIntro: "See the questionnaire as respondents would. The printed preview has the same pages as the PDF.",
  previewLegend: "Show",
  desktop: "Desktop preview",
  mobile: "Mobile preview",
  print: "Printed questionnaire preview",
  word: "Microsoft Word preview",
  mobileNote: "Shown at 375 pixels wide, a common phone width.",
  formNote: "Try the controls: nothing you choose here is saved.",
  wordNote: "Word decides where most pages break. Only the break after the cover page is fixed, so page breaks may differ from the printed preview.",
  pageLabel: (page: number, total: number) => `Page ${page} of ${total}`,
  continues: "Continues on the next page.",
  pageBreak: "Page break",
  export: "Export",
  exportIntro: "Every format keeps the numbering, sections, headings and scale tables.",
  docx: "Download Word (.docx)",
  pdf: "Download PDF",
  markdown: "Download Markdown",
  text: "Download plain text",
  copyLabel: "Copy questionnaire",
  copiedLabel: "Copied questionnaire",
  copySubject: "as plain text",
  projectDraft: "Your project draft",
  projectDraftIntro: "This tool writes only the Questionnaire section. Everything else is shown as you entered it.",
  guide: "Question types and scales explained",
  guideIntro: "Every question type and scale the builder offers. References will be added after academic review.",
  typesHeading: "Question types",
  scalesHeading: "Scales",
  sectionsHeading: "Sections",
  suits: "Usually gives",
  noLevels: "Not a measurement.",
  instruction: "Respondents are told",
  referencesPending: "References awaiting academic review.",
} as const;
