/** All wording for the Sample Size Calculator. Academic content lives in the knowledge layer. */

export const page = {
  title: "Sample Size Calculator",
  /** One sentence, for listings such as the tools index. */
  summary: "Works out a sample size from your assumptions, shows every step of the working, and explains what each assumption means.",
  metaDescription:
    "Calculate a sample size with Cochran's formula, the finite population correction, Yamane's formula or Krejcie and Morgan, then see the full working, every assumption, and how the result changes when the assumptions change.",
  intro:
    "Choose a method, enter your assumptions, and see the sample size they give, with every step of the working. Nothing here is universally correct: a different confidence level, margin of error, proportion or response rate gives a different number, so the calculator shows those alternatives together and explains each assumption.",
  noScript:
    "The Sample Size Calculator works out results as you type, which needs JavaScript. Turn on JavaScript to use it. The guide to the methods below works without it.",
  howHeading: "How the calculator works",
  limitsHeading: "What this tool can't do",
  reviewHeading: "Awaiting review",
  privacyHeading: "Privacy",
  privacy: "Everything stays in your browser. Nothing is sent anywhere or saved, and it is cleared when you leave the page.",
} as const;

export const how: readonly string[] = [
  "The calculator reads your project draft: research question, objectives, variables, hypotheses, research design and sampling plan. Enter them in the first step; later versions will bring them across from the other research tools.",
  "Every result shows its formula, the numbers substituted, the intermediate values and how it was rounded, so you can check it by hand.",
  "The sensitivity tables show how the result changes under other common assumptions. They describe the differences; they don't recommend any of them.",
  "Checks compare your inputs with your project and explain what to look at. They never score or rank your choices.",
  "The calculator writes only the sample size section of your project draft: the method and assumptions, not the numbers, so later tools recalculate rather than copy.",
];

export const steps = {
  project: "Project details",
  projectIntro: "Enter what you already know. Anything left blank is simply not compared.",
  example: "Load an example project",
  exampleLoaded: "Example project loaded. It is fictional, for trying the calculator.",
  question: "Research question",
  objectives: "Research objectives",
  perLine: "One per line.",
  independent: "Independent variables",
  dependent: "Dependent variables",
  outcomeLevel: "Dependent variables are measured as",
  outcomeLevelHint: "The measurement level from the Variables Builder, if you used it.",
  notChosen: "Not chosen",
  design: "Research design",
  designHint: "Your chosen design from the Research Design Builder, if you used it.",
  technique: "Sampling technique",
  techniqueHint: "Your chosen technique from the Sampling Technique Builder, if you used it.",
  targetPopulation: "Target population",
  samplingFrame: "Sampling frame",
  planResponseRate: "Expected response rate in your sampling plan (%)",
  hypothesesLegend: "Hypotheses",
  hypothesesHint: "Until the tools share a saved project, the calculator can draft hypotheses from your variables with the Hypothesis Builder's rules.",
  withHypotheses: "Draft hypotheses from these details",
  withoutHypotheses: "No hypotheses",
  method: "Method",
  methodIntro: "Each method answers a slightly different question. Read what each assumes; the guide at the end explains them in full.",
  methodLegend: "Which method will you use?",
  notAvailable: "not calculated here",
  inputs: "Your assumptions",
  inputsIntro: "Every input changes the result. Open “What this means” under each to see when it matters, typical values and its limitations.",
  populationLegend: "Population",
  finite: "Known size",
  unknown: "Unknown or very large",
  populationSize: "Population size",
  confidence: "Confidence level",
  margin: "Margin of error (%)",
  proportion: "Estimated proportion (%)",
  responseRate: "Expected response rate (%)",
  responseRateHint: "Leave blank if you haven't estimated it yet.",
  useSamplingRate: (rate: string) => `Use your sampling plan's rate (${rate}%)`,
  designEffect: "Design effect",
  explain: "What this means",
  meaning: "What it means",
  whenMatters: "When it matters",
  typicalValues: "Typical values",
  limitations: "Limitations",
  result: "Result",
  resultIntro: "What your assumptions give. The number follows from them; it isn't correct in general.",
  cannotCalculate: "The sample size can't be calculated yet:",
  powerNotAvailable:
    "Power analysis isn't calculated here. It needs the effect size you want to detect, the significance level and the power, and a formula specific to your statistical test. The guide explains it.",
  required: "Required sample size",
  adjusted: "After the design effect",
  invite: "People to invite",
  expected: "Expected responses",
  fraction: "Share of the population",
  noRate: "Add a response rate",
  workingHeading: "The working, step by step",
  formula: "Formula",
  substitution: "Substitution",
  unrounded: "Result",
  usedAs: "used as",
  inputChecks: "About your inputs",
  noInputChecks: "Nothing further to note about your inputs.",
  assumptions: "Assumptions behind this result",
  assumptionsIntro: "Each assumption, its value, and where it comes from in your project.",
  source: "Source",
  compatibility: "How the calculation fits your project",
  compatibilityIntro: "Each check explains why, and names the parts of your project behind it.",
  supports: "Based on",
  sensitivity: "How the result changes with other assumptions",
  sensitivityIntro:
    "The same calculation under other common assumptions, everything else unchanged. None of these is recommended; they show what your choice of assumptions costs or saves.",
  sensitivityEmpty: "Fix your inputs, or choose a method the calculator computes, to see alternatives.",
  scenario: "Assumption",
  yours: "Your current assumptions",
  justification: "Your justification and report",
  justificationLabel: "Justification",
  justificationHint: "Why these assumptions suit your study: where the population count, proportion and response rate come from.",
  notes: "Notes (optional)",
  copyLabel: "Copy sample size report",
  copiedLabel: "Copied sample size report",
  copySubject: "as text for a thesis proposal",
  preview: "Preview the report",
  projectDraft: "Your project draft",
  projectDraftIntro: "This tool writes only the Sample size section. Everything else is shown as you entered it.",
  guide: "Sample size methods explained",
  guideIntro: "Every method the calculator covers. References for each will be added after academic review.",
  learnMore: (name: string) => `Learn more about ${name}`,
  formulaHeading: "Formula",
  whenUsed: "When it is commonly used",
  assumptionsHeading: "Assumptions",
  strengths: "Strengths",
  references: "References",
  referencesPending: "References awaiting academic review.",
} as const;
