/** All wording for the Variables Builder. Academic content lives in the knowledge layer. */

export const page = {
  title: "Variables Builder",
  /** One sentence, for listings such as the tools index. */
  summary: "Brings your variables together from your project, and helps you define, operationalise and measure each one.",
  metaDescription:
    "Identify, define and operationalise your research variables: conceptual and operational definitions, indicators, measurement levels and scales, linked to your question, objectives, hypotheses and framework.",
  intro:
    "Your variables are gathered from your project details, hypotheses and conceptual framework, so nothing needs retyping. For each one, work from concept to measurement: definitions, indicators, measurement level and scale. Every check explains itself, and nothing is written for you.",
  noScript:
    "The Variables Builder works in your browser, which needs JavaScript. Turn on JavaScript to use it. The guide to variable types and measurement levels below works without it.",
  howHeading: "How the builder works",
  limitsHeading: "What this tool can't do",
  reviewHeading: "Awaiting review",
  privacyHeading: "Privacy",
  privacy: "Everything stays in your browser. Nothing is sent anywhere or saved, and it is cleared when you leave the page.",
} as const;

export const how: readonly string[] = [
  "The builder reads your project draft: research question, aim, objectives, hypotheses and conceptual framework. Enter them in the first step; later versions will bring them across from the other research tools.",
  "Every variable named anywhere in your project is imported once, and the builder shows where each one came from.",
  "Unknown information stays as a placeholder in square brackets, such as “[conceptual definition]”. The builder never writes definitions, indicators or items for you.",
  "The builder writes only the variables section of your project draft. Later tools will read your variables from there instead of keeping their own copies.",
];

export const steps = {
  project: "Project details",
  projectIntro: "Enter what you already know. Each variable should be named exactly as elsewhere in your project, one per line.",
  example: "Load an example project",
  exampleLoaded: "Example project loaded. It is fictional, for trying the builder.",
  question: "Research question",
  aim: "Research aim",
  objectives: "Research objectives",
  perLine: "One per line.",
  independent: "Independent variables",
  dependent: "Dependent variables",
  mediator: "Mediator variables (optional)",
  moderator: "Moderator variables (optional)",
  control: "Control variables (optional)",
  population: "Population",
  methodology: "Methodology (optional)",
  notChosen: "Not chosen",
  hypothesesLegend: "Hypotheses and framework",
  hypothesesHint:
    "Until the tools share a saved project, the builder can draft hypotheses with the Hypothesis Builder's rules and a framework with the Conceptual Framework Builder's rules, so your variables link to them.",
  withHypotheses: "Draft hypotheses and a framework from these details",
  withoutHypotheses: "No hypotheses or framework",
  variables: "Your variables",
  variablesIntro: "Select a variable to edit it. The table lists every variable and where it came from.",
  tableCaption: "Variables in your project",
  columns: { name: "Variable", kind: "Type", level: "Measurement level", indicators: "Indicators", origin: "Where it came from", edit: "Edit" },
  editButton: (name: string) => `Edit ${name}`,
  noVariables: "No variables yet. Add them in your project details above, or add one below.",
  importNew: (count: number) => `Import ${count} new ${count === 1 ? "variable" : "variables"} from your project`,
  edited: "You have edited your variables, so new variables in your project details aren't added automatically.",
  undo: "Undo",
  addHeading: "Add a variable",
  newName: "Name",
  newKind: "Type",
  add: "Add variable",
  setChecks: "Checks across all variables",
  editor: "Edit a variable",
  choose: "Variable to edit",
  origin: "Where it came from",
  connections: "How it connects",
  inQuestion: "Named in your research question.",
  notInQuestion: "Not named in your research question.",
  objectivesCount: (count: number) => (count === 0 ? "Not named in any objective." : `Named in ${count} ${count === 1 ? "objective" : "objectives"}:`),
  hypothesesCount: (count: number) => (count === 0 ? "Not named in any hypothesis." : `Named in ${count} ${count === 1 ? "hypothesis" : "hypotheses"}.`),
  frameworkBox: (type: string, relationships: number) =>
    `Shown in your conceptual framework (${type.toLowerCase()}), with ${relationships} ${relationships === 1 ? "relationship" : "relationships"}.`,
  noFramework: "Not shown in your conceptual framework.",
  details: "Definition and measurement",
  name: "Name",
  shortName: "Short name",
  shortNameHint: "Used in tables and figures.",
  kind: "Type",
  description: "Description (optional)",
  conceptual: "Conceptual definition",
  conceptualHint: "What the variable means, usually drawn from the literature.",
  operational: "Operational definition",
  operationalHint: "Exactly how it will be observed or measured in your study.",
  level: "Measurement level",
  scale: "Measurement scale",
  scaleHint: "The answer options, range or unit, such as “1 = strongly disagree to 5 = strongly agree”.",
  items: "Possible questionnaire items",
  itemsHint: "In your own words, one per line.",
  notes: "Notes (optional)",
  indicators: "Indicators",
  indicatorsIntro: "Indicators are observable signs of the variable that you can measure. List them in the order you want them.",
  indicatorLegend: (position: number, name: string) => `Indicator ${position}: ${name}`,
  indicatorName: (position: number) => `Name of indicator ${position}`,
  indicatorDescription: (position: number) => `Description of indicator ${position} (optional)`,
  indicatorMeasurement: (position: number) => `How indicator ${position} is measured`,
  indicatorScale: (position: number) => `Scale of indicator ${position}`,
  indicatorLevel: (position: number) => `Measurement level of indicator ${position}`,
  moveUp: (name: string) => `Move ${name} up`,
  moveDown: (name: string) => `Move ${name} down`,
  deleteIndicator: (name: string) => `Delete ${name}`,
  newIndicator: "New indicator",
  addIndicator: "Add indicator",
  chain: "Operationalisation",
  chainIntro: "From concept to questionnaire item. Square brackets show what is still unknown.",
  draftItems: "Draft item structures",
  draftItemsIntro: "One structure per indicator, naming only the indicator and answer format. Write the wording yourself.",
  checks: "Checks",
  duplicate: (name: string) => `Duplicate ${name}`,
  deleteVariable: (name: string) => `Delete ${name}`,
  missingTag: "Missing",
  why: "Why:",
  export: "Copy your variables",
  exportIntro: "Copies a table of your variables, which pastes into word processors and spreadsheets.",
  copySubject: "variables table",
  projectDraft: "Your project draft",
  projectDraftIntro: "This tool writes only the Variables section. Everything else is shown as you entered it.",
  guide: "Variable types and measurement levels",
  guideIntro: "A reference for choosing types and levels. References for each will be added after academic review.",
  kindsHeading: "Variable types",
  levelsHeading: "Measurement levels",
  example2: "Example",
  examples: "Examples",
  strengths: "Strengths",
  limitations: "Limitations",
  references: "References",
  referencesPending: "References awaiting academic review.",
  learnMore: (name: string) => `Learn more about ${name.toLowerCase()}`,
} as const;
