/** All wording for the Literature Matrix Builder. Academic content lives in the knowledge layer. */

export const page = {
  title: "Literature Matrix Builder",
  /** One sentence, for listings such as the tools index. */
  summary: "Organise, compare and synthesise the studies in your literature review, and see the repeated methods, variables and gaps across them.",
  metaDescription:
    "Build a literature review matrix for a thesis, dissertation or systematic review: import BibTeX, RIS or CSV, compare studies' designs, samples, variables and findings, find repeated methods and research gaps, and export to Word, Excel or PDF.",
  intro:
    "Record each study you read in one matrix: its context, methods, variables, findings and gaps, with your own reflection. The builder finds what recurs across studies, explains why such patterns are common, and points out gaps worth checking.",
  noScript:
    "The matrix needs JavaScript. Turn on JavaScript to use the builder. The guide to the matrix columns and the patterns it finds, below, works without it.",
  howHeading: "How the builder works",
  limitsHeading: "What this tool can't do",
  reviewHeading: "Awaiting review",
  privacyHeading: "Privacy",
  privacy: "Everything stays in your browser. Nothing is sent anywhere or saved, and it is cleared when you leave the page, so export your matrix to keep it.",
} as const;

export const how: readonly string[] = [
  "Add your project details if you like: the matrix shows which of your variables each study covers, and your topic, question, objectives and hypotheses stay in view as you read.",
  "Add studies one at a time, or import them from BibTeX or RIS files exported by your reference manager, or from a CSV or spreadsheet.",
  "Fill in each study's context, methods, variables, findings and gaps as you read it, with your own critical reflection. Tag, star and prioritise studies, and track what you have read.",
  "Search, sort and filter the matrix, and choose which columns to see. Compare any two studies side by side.",
  "Patterns and gaps update as you go: repeated variables, designs, samples, analyses and theories, each explained, and the gaps the studies name or the matrix suggests.",
  "Export the matrix to Word, PDF, Excel, CSV, Markdown or HTML, and copy the synthesis into your literature review as a starting point.",
];

export const steps = {
  project: "Your project",
  projectIntro: "Optional. Your project details are shown beside the matrix and used to find which of your variables each study covers, and which none do.",
  projectToggle: "Add your project details",
  topic: "Research topic",
  exampleProject: "Load an example project",
  exampleProjectLoaded: "Example project loaded. It is fictional, for trying the builder.",
  fromProject: "From your project",
  projectRows: { topic: "Topic", question: "Research question", objectives: "Objectives", hypotheses: "Hypotheses", variables: "Variables" } as Record<string, string>,

  add: "Add studies",
  addIntro: "Add a study and fill it in as you read, or import studies from your reference manager.",
  addStudy: "Add a study",
  loadExample: "Load example matrix",
  exampleNote: "The example studies are fictional, for trying the builder.",
  importHeading: "Import",
  importFormat: "Import from",
  formats: { bibtex: "BibTeX (.bib)", ris: "RIS (.ris)", csv: "CSV or spreadsheet", doi: "DOI" } as Record<string, string>,
  importText: "Paste the text",
  importHint: { bibtex: "Export BibTeX from Zotero, Mendeley, EndNote or Google Scholar, and paste it here or choose the file.", ris: "Export RIS from your reference manager or database, and paste it here or choose the file.", csv: "Paste a spreadsheet or CSV with column names in the first row, such as Author(s), Year and Title. A CSV exported from this builder imports completely.", doi: "" } as Record<string, string>,
  doiLabel: "DOI",
  doiHint: "Such as 10.1177/0013189X17739591. The study is added with its DOI; filling in the other details from the DOI isn't available yet.",
  chooseFile: "Or choose a file",
  importButton: "Import studies",
  addDoi: "Add study by DOI",

  matrix: "Your matrix",
  empty: "No studies yet. Add a study, import some, or load the example matrix.",
  search: "Search the matrix",
  searchHint: "Finds studies containing every word, in any column.",
  sortBy: "Sort by",
  yourOrder: "Your order",
  direction: "Direction",
  directions: { ascending: "Ascending", descending: "Descending" } as Record<string, string>,
  filters: "Filter",
  status: "Reading status",
  priority: "Priority",
  tag: "Colour tag",
  any: "Any",
  none: "None",
  favouritesOnly: "Favourites only",
  fromYear: "From year",
  toYear: "To year",
  columns: "Columns",
  columnsToggle: (shown: number, total: number) => `Choose columns (${shown} of ${total} shown)`,
  presets: "Show a set of columns",
  caption: (shown: number, total: number) => (shown === total ? `Literature matrix: ${total} ${total === 1 ? "study" : "studies"}` : `Literature matrix: ${shown} of ${total} studies shown`),
  noMatches: "No study matches the search and filters.",
  study: "Study",
  actions: "Actions",
  edit: (label: string) => `Edit ${label}`,
  duplicate: (label: string) => `Duplicate ${label}`,
  moveUp: (label: string) => `Move ${label} up`,
  moveDown: (label: string) => `Move ${label} down`,
  remove: (label: string) => `Delete ${label}`,
  favourite: (label: string) => `Favourite ${label}`,
  reorderNote: "To reorder studies by hand, choose “Your order” and clear the search and filters.",
  checks: "Checks",
  covers: "Covers your variables",

  editor: (label: string) => `Editing ${label}`,
  organisation: "Organisation",
  closeEditor: "Done",
  undo: "Undo delete",

  insights: "Patterns and gaps",
  insightsIntro: "What recurs across the studies, and why such patterns are usual. Reasons are the common reasons researchers make each choice; check each study for its own.",
  repeated: "Found in two or more studies",
  seenIn: "Studies",
  nothingRepeated: "Nothing recurs yet.",
  statedGaps: "Gaps the studies name",
  statedIntro: "Gaps, limitations and recommendations that several studies state in similar words.",
  noStated: "No gap is named by more than one study yet.",
  potentialGaps: "Potential gaps",
  potentialIntro: "What the matrix as a whole suggests may be missing. These are prompts to check against a wider search, not conclusions.",
  noPotential: "No potential gaps stand out yet. Patterns need at least three studies.",
  evidence: "Evidence",
  why: "Why it may matter",
  synthesis: "Synthesis",
  synthesisIntro: "A description of the matrix in words, to adapt into your literature review.",
  copySynthesis: "Copy synthesis",
  copiedSynthesis: "Copied synthesis",

  compare: "Compare two studies",
  compareIntro: "Choose two studies to see them side by side.",
  first: "First study",
  second: "Second study",
  choose: "Choose a study",
  shared: "In common",
  sharedVariables: "Variables",
  sharedMethods: "Methods",
  sharedTheories: "Theories",
  nothingShared: "None",
  relations: { same: "Same", different: "Different", missing: "Not given" } as Record<string, string>,
  comparison: "Comparison",
  column: "Column",

  export: "Export",
  exportIntro: "Files use the columns currently shown, and every study, whatever the search and filters. Excel and CSV also keep each study's status, priority, tag and favourite mark, so they import back completely.",
  exportTitle: "Title for exported files",
  download: (format: string) => `Download ${format}`,
  wideWarning: (columns: number) => `${columns} columns make a very small printed table. For Word and PDF, choose fewer columns, such as a preset.`,

  guide: "Matrix columns and patterns",
  guideIntro: "What to record in each column, and how the builder finds patterns and gaps.",
  guideColumns: "Columns",
  guidePatterns: "How patterns and gaps are found",
  guidePatternItems: [
    "Designs, sampling techniques, analyses, philosophies and approaches are recognised by their usual names, such as “stratified random”, “PLS-SEM” or “interpretivist”, and matched to the catalogues the other research tools use.",
    "Variables, theories and countries are counted by their wording, ignoring case, accents and bracketed abbreviations; theories named in a study's context, problem, contribution or notes also count.",
    "A pattern is anything found in two or more studies; each study counts once.",
    "Stated gaps are grouped when statements from different studies share at least two key words, and at least half of the shorter statement's key words.",
    "Potential gaps need at least three studies. They flag a design, setting or sampling approach used by 60% or more of the studies reporting it, a median quantitative sample below 100, no study in the last five years, theory named by fewer than half the studies, mediators and moderators in under 20% of relationship studies, and your project's variables or relationships that no study covers.",
  ],
} as const;
