/** All wording for the Sampling Technique Builder. Academic content lives in the knowledge layer. */

export const page = {
  title: "Sampling Technique Builder",
  /** One sentence, for listings such as the tools index. */
  summary: "Helps you define your population and understand, compare and justify sampling techniques, without choosing one for you.",
  metaDescription:
    "Define your population and compare 13 probability and non-probability sampling techniques against your research question, design, variables and objectives. Every judgement is explained; the choice stays yours.",
  intro:
    "Define who you want to study, answer a few questions about your situation, and see how each sampling technique fits your research question, design and population. Compare techniques side by side, then choose one and write your sampling plan. The builder never chooses for you.",
  noScript:
    "The Sampling Technique Builder responds to your project and answers, which needs JavaScript. Turn on JavaScript to use it. The guide to sampling techniques below works without it.",
  howHeading: "How the builder works",
  limitsHeading: "What this tool can't do",
  reviewHeading: "Awaiting review",
  privacyHeading: "Privacy",
  privacy: "Everything stays in your browser. Nothing is sent anywhere or saved, and it is cleared when you leave the page.",
} as const;

export const how: readonly string[] = [
  "The builder reads your project draft: research question, objectives, variables, hypotheses, research design and research onion choices. Enter them in the first step; later versions will bring them across from the other research tools.",
  "Your answers to the decision questions only narrow the explanations. Every technique stays available, and none is ever chosen for you.",
  "Compatibility checks compare each technique with your project and population, and say why it fits, what it assumes, and what to justify. They never rank or score techniques.",
  "The builder writes only the sampling plan section of your project draft, which later tools, such as the sample size calculator and questionnaire builder, will read.",
];

export const steps = {
  project: "Project details",
  projectIntro: "Enter what you already know. Anything left blank is simply not compared.",
  example: "Load an example project",
  exampleLoaded: "Example project loaded. It is fictional, for trying the builder.",
  question: "Research question",
  objectives: "Research objectives",
  perLine: "One per line.",
  independent: "Independent variables",
  dependent: "Dependent variables",
  onionHeading: "Research onion choices",
  onionHint: "Use the same choices as in the Research Onion Explorer, if you used it.",
  design: "Research design",
  designHint: "Your chosen design from the Research Design Builder, if you used it.",
  notChosen: "Not chosen",
  hypothesesLegend: "Hypotheses",
  hypothesesHint: "Until the tools share a saved project, the builder can draft hypotheses from your variables with the Hypothesis Builder's rules.",
  withHypotheses: "Draft hypotheses from these details",
  withoutHypotheses: "No hypotheses",
  population: "Your population",
  populationIntro: "Who your findings are about, who you can reach, and how you will find them.",
  criteriaHint: "One per line.",
  decision: "Your situation",
  decisionIntro: "Answer what you can. Your answers explain how each technique relates to your situation; they don't choose one.",
  yes: "Yes",
  no: "No",
  unsure: "Not sure",
  relatesHeading: "How techniques relate to your answers",
  filterLegend: "Show",
  showAll: "All techniques",
  showConsistent: "Only techniques consistent with every answer",
  noneConsistent: "No technique fits every answer. Look at where each differs; your situation may need a compromise, which your plan should explain.",
  fitsTag: "Fits your answer",
  differsTag: "Differs from your answer",
  shortlistAdd: (name: string) => `Add ${name} sampling to shortlist`,
  shortlisted: "On your shortlist",
  shortlist: "Your shortlist",
  shortlistIntro: "Add the techniques you want to consider. Compare them below, then choose one yourself.",
  addTechnique: "Add a technique",
  add: "Add to shortlist",
  choose: "Choose",
  noShortlist: "Your shortlist is empty. Add techniques from the list above or here.",
  remove: (name: string) => `Remove ${name} sampling`,
  compatibility: "How each technique fits your project",
  compatibilityIntro: "Each check explains why, names the parts of your project behind it, and says what you should justify.",
  supports: "Supported by",
  justify: "What to justify:",
  assumptions: "What this technique assumes",
  supportingHeading: "Why this technique could support your project",
  noSupport: "No part of your project clearly supports this technique yet.",
  comparison: "Compare techniques",
  comparisonIntro: "Your shortlisted techniques side by side.",
  comparisonEmpty: "Add at least two techniques to your shortlist to compare them.",
  comparisonCaption: "Comparison of shortlisted sampling techniques",
  aspect: "Aspect",
  copyLabel: "Copy table",
  copiedLabel: "Copied table",
  copySubject: "of the comparison",
  plan: "Your sampling plan",
  chosenLegend: "Which technique will you use?",
  chosenHint: "This is your decision. Compare the techniques and read the checks first.",
  noChoice: "Not decided yet",
  reason: "Reason for this technique",
  reasonHint: "Why it suits your question, design and population, and how you will handle its limitations.",
  procedure: "Sample selection procedure",
  procedureHint: "Step by step, how participants will be identified, selected and invited.",
  responseRate: "Expected response rate (%)",
  responseRateHint: "What share of the people you invite you expect to take part, such as 60. Base it on similar studies or a pilot.",
  biases: "Potential biases",
  mitigation: "Mitigation strategy",
  notes: "Notes (optional)",
  checks: "Checks",
  planCopyLabel: "Copy plan",
  planCopiedLabel: "Copied plan",
  planCopySubject: "as text",
  projectDraft: "Your project draft",
  projectDraftIntro: "This tool writes only the Sampling plan section. Everything else is shown as you entered it.",
  guide: "Sampling techniques explained",
  guideIntro: "Every technique the builder covers. References for each will be added after academic review.",
  learnMore: (name: string) => `Learn more about ${name.toLowerCase()} sampling`,
  whenUsed: "When it is commonly used",
  strengths: "Strengths",
  limitations: "Limitations",
  assumptionsHeading: "Assumptions",
  sizes: "Common sample sizes",
  examples: "Examples",
  references: "References",
  referencesPending: "References awaiting academic review.",
} as const;
