/** Wording for the statistics teaching components shared by the Statistical Test Finder and the Statistics guides. */

export const statisticsCopy = {
  tree: {
    caption: "Choosing a statistical test: a decision tree",
    intro: "Follow the questions from the top. Each path ends in the tests commonly used for that situation. It shows common practice, not the only valid choice.",
    common: "Commonly used:",
    also: "May also fit:",
    none: "No test in this guide covers this path.",
  },
  matrix: {
    caption: "Common statistical tests compared",
    scrollHint: "The table scrolls sideways on narrow screens.",
  },
  table: {
    scrollHint: "Scroll sideways to see every column.",
  },
  example: {
    question: "Research question",
    variables: "Variables",
    groups: "Groups",
    structure: "Structure",
    candidate: "A candidate test",
    why: "Why it may fit",
    assumptions: "Assumptions to check",
    data: "Illustrative data",
    working: "Worked from the data",
    interpretation: "What the result would tell you",
    level: (label: string) => `${label} level`,
  },
  profile: {
    answers: "What question it answers",
    structure: "Data it needs",
    outcome: "Outcome",
    predictor: "Predictor or grouping variable",
    groups: "Groups",
    pairing: "Independent or paired",
    fits: "Why it may fit",
    whyNot: "Why a similar test may not fit",
    assumptions: "Key assumptions",
    hypotheses: "Hypotheses",
    nullHypothesis: "Null hypothesis (H₀)",
    alternativeHypothesis: "Alternative hypothesis (H₁)",
    example: "Example question",
    limitations: "Limitations",
    alternatives: "Alternatives",
    mistakes: "Common mistakes",
    reporting: "Introducing the result in a report",
    formulas: "Formulas",
    notCovered: "The Statistical Assumption Checker doesn't have a guide for this test yet; these assumptions come from the analysis catalogue.",
  },
  formula: {
    symbols: "Where",
  },
  figures: {
    illustrative: "Illustrative",
    compared: "compared with",
  },
  descriptive: {
    dataCaption: "Days of training attended by nine employees (invented for illustration)",
    employee: "Employee",
    days: "Days",
    summaryCaption: "Summaries of the training days",
    statistic: "Statistic",
    value: "Value",
    working: "Working",
    meaning: "What it tells you",
  },
} as const;
