export { ComparisonMatrix } from "./comparison-matrix";
export { DataTable } from "./data-table";
export { DecisionTreeView } from "./decision-tree";
export { DescriptiveExample } from "./descriptive-example";
export { StructureDiagramView, TeachingFigure } from "./figures";
export { FormulaList } from "./formula-list";
export { TestProfileView } from "./test-profile";
export { WorkedExampleView } from "./worked-example";
export { SpssProcedureView } from "./spss-procedure";
export { SpssWorkflow } from "./spss-workflow";
