/** All wording for the Research Design Builder. Academic content lives in the knowledge layer. */

export const page = {
  title: "Research Design Builder",
  /** One sentence, for listings such as the tools index. */
  summary: "Helps you understand, compare and justify research designs against your own project, without choosing one for you.",
  metaDescription:
    "Compare 21 research designs, from experiments to mixed methods, against your research question, research onion choices, variables, objectives and hypotheses. Every judgement is explained; the choice stays yours.",
  intro:
    "Answer a few questions about your plans, shortlist the designs worth considering, and see how each fits your research question, research onion choices, variables, objectives, hypotheses and framework. Compare them side by side, then choose and justify your design. The builder never chooses for you.",
  noScript:
    "The Research Design Builder responds to your project and answers, which needs JavaScript. Turn on JavaScript to use it. The guide to research designs below works without it.",
  howHeading: "How the builder works",
  limitsHeading: "What this tool can't do",
  reviewHeading: "Awaiting review",
  privacyHeading: "Privacy",
  privacy: "Everything stays in your browser. Nothing is sent anywhere or saved, and it is cleared when you leave the page.",
} as const;

export const how: readonly string[] = [
  "The builder reads your project draft: research question, objectives, variables, hypotheses, conceptual framework and research onion choices. Enter them in the first step; later versions will bring them across from the other research tools.",
  "Your answers to the decision questions only narrow the explanations. Every design stays available, and none is ever chosen for you.",
  "Compatibility checks compare each design with your project and say why it fits, what it assumes, and what you should justify. They never rank or score designs.",
  "The builder writes only the research design section of your project draft, which later tools, such as sampling and data analysis planning, will read.",
];

export const steps = {
  project: "Project details",
  projectIntro: "Enter what you already know. Anything you leave blank is simply not compared.",
  example: "Load an example project",
  exampleLoaded: "Example project loaded. It is fictional, for trying the builder.",
  question: "Research question",
  objectives: "Research objectives",
  perLine: "One per line.",
  independent: "Independent variables",
  dependent: "Dependent variables",
  onionHeading: "Research onion choices",
  onionHint: "Use the same choices as in the Research Onion Explorer, if you used it.",
  notChosen: "Not chosen",
  hypothesesLegend: "Hypotheses and framework",
  hypothesesHint: "Until the tools share a saved project, the builder can draft hypotheses and a framework from your variables with the other builders' rules.",
  withHypotheses: "Draft hypotheses and a framework from these details",
  withoutHypotheses: "No hypotheses or framework",
  decision: "Your plans",
  decisionIntro: "Answer what you can. Your answers explain how each design relates to your plans; they don't choose one.",
  unsure: "Not sure",
  relatesHeading: "How designs relate to your answers",
  showAll: "All designs",
  showConsistent: "Only designs consistent with every answer",
  filterLegend: "Show",
  noneConsistent: "No design fits every answer. Look at where each differs; your plans may need rethinking, or a design can be adapted.",
  fitsTag: "Fits your answer",
  differsTag: "Differs from your answer",
  noAnswers: "Answer a question above to see how each design relates to it.",
  shortlistAdd: (name: string) => `Add ${name} to shortlist`,
  shortlisted: "On your shortlist",
  shortlist: "Your shortlist",
  shortlistIntro: "Add the designs you want to consider. Compare them below, then choose one yourself.",
  addDesign: "Add a design",
  add: "Add to shortlist",
  choose: "Choose a design",
  noShortlist: "Your shortlist is empty. Add designs from the list above or here.",
  remove: (name: string) => `Remove ${name}`,
  chosenLegend: "Which design will you use?",
  chosenHint: "This is your decision. Compare the designs and read the checks first.",
  noChoice: "Not decided yet",
  compatibility: "How each design fits your project",
  compatibilityIntro: "Each check explains why, names the parts of your project behind it, and says what you should justify.",
  supports: "Supported by",
  justify: "What to justify:",
  assumptions: "What this design assumes",
  supportingHeading: "Project elements that support this design",
  noSupport: "No part of your project clearly supports this design yet.",
  comparison: "Compare designs",
  comparisonIntro: "Your shortlisted designs side by side.",
  comparisonEmpty: "Add at least two designs to your shortlist to compare them.",
  comparisonCaption: "Comparison of shortlisted research designs",
  aspect: "Aspect",
  /** Visible label and hidden subject read together as “Copy table (comparison)”. */
  copyLabel: "Copy table",
  copiedLabel: "Copied table",
  copySubject: "of the comparison",
  justification: "Justify your design",
  justificationLabel: "Design justification",
  justificationHint: "Why this design suits your question, objectives and circumstances, what it assumes, and how you will handle its limitations.",
  notesLabel: "Notes (optional)",
  checks: "Checks",
  projectDraft: "Your project draft",
  projectDraftIntro: "This tool writes only the Research design section. Everything else is shown as you entered it.",
  guide: "Research designs explained",
  guideIntro: "Every design the builder covers. References for each will be added after academic review.",
  learnMore: (name: string) => `Learn more about ${name.toLowerCase()} designs`,
  purpose: "Purpose",
  whenUsed: "When it is commonly used",
  strengths: "Strengths",
  limitations: "Limitations",
  typicalData: "Typical data",
  analysis: "Common analysis methods",
  examples: "Examples",
  references: "References",
  referencesPending: "References awaiting academic review.",
} as const;
