/** All wording for the PRISMA Flow Diagram Builder. Academic content lives in the knowledge layer. */

export const page = {
  title: "PRISMA Flow Diagram Builder",
  /** One sentence, for listings such as the tools index. */
  summary: "Draws PRISMA 2020 flow diagrams for systematic, scoping and rapid reviews, checks that every number adds up, and exports sharp SVG, PNG and PDF files.",
  metaDescription:
    "Make a PRISMA 2020 flow diagram for a systematic review, scoping review or meta-analysis: enter or count your records, check the numbers add up, edit wording and arrows, and export SVG, 300 DPI PNG or PDF for Word and journals.",
  intro:
    "Enter the numbers from your searches and screening, or count records straight from your exported files. The builder calculates each stage, checks that everything adds up, and draws a publication-ready PRISMA flow diagram with a text alternative and a paragraph you can adapt for your methods.",
  noScript:
    "Drawing the diagram needs JavaScript. Turn on JavaScript to use the builder. The guide below, to the diagram's boxes and the checks, works without it.",
  howHeading: "How the builder works",
  limitsHeading: "What this tool can't do",
  reviewHeading: "Awaiting review",
  privacyHeading: "Privacy",
  privacy: "Everything stays in your browser. Nothing is sent anywhere or saved, and it is cleared when you leave the page.",
} as const;

export const how: readonly string[] = [
  "Choose the diagram: PRISMA 2020, PRISMA-S (every source listed), a scoping review, a rapid review, or a simpler narrative review workflow. Add the other methods column if you also searched websites, organisations or citations.",
  "Enter the records identified, or count them from the BibTeX, RIS or CSV files your databases exported; duplicates across the files are found for you.",
  "Enter what was removed and excluded at each stage, with the reasons reports were excluded. Stages left blank are calculated from those before them.",
  "The checks show at once where numbers don't add up, go missing, turn negative or run out of order, each with how to fix it.",
  "Change any box's wording, hide or label arrows, and choose orientation, colour, grayscale or high contrast, and the typeface.",
  "Export SVG or PDF, which stay sharp at any size, or a 300 DPI PNG, or copy the diagram straight into Word or PowerPoint, with its text alternative and a paragraph describing the flow.",
];

export const steps = {
  setup: "Diagram",
  kind: "Diagram type",
  otherMethods: "Other methods column",
  otherMethodsHint: "For records found by searching websites, organisations or citations, which PRISMA 2020 shows in a column of their own.",
  onOff: { on: "Show", off: "Hide" } as Record<string, string>,
  topic: "Review title or topic",
  topicHint: "Used in the diagram's title, such as “PRISMA 2020 flow diagram: Screen use and sleep”.",
  loadExample: "Load example numbers",
  exampleLoaded: "Example numbers loaded. They are fictional, for trying the builder.",

  numbers: "Numbers",
  identification: "Identification",
  databases: "Databases",
  registers: "Registers",
  otherSources: "Other methods",
  sourceName: "Name",
  sourceCount: "Records",
  addSource: (noun: string) => `Add ${noun}`,
  removeSource: (name: string) => `Remove ${name}`,
  countFromFiles: "Count records from exported files",
  countIntro: "Paste or choose the BibTeX, RIS or CSV file each database exported. Records are counted, and duplicates across the files found by DOI or by title and year.",
  exportName: "Database or register",
  exportFormat: "Format",
  exportText: "Exported records",
  addExport: "Add another file",
  countButton: "Count records",
  useCounts: "Use these counts",
  countResult: (total: number, duplicates: number, unique: number) => `${total} records, ${duplicates} duplicates, ${unique} after removing duplicates.`,
  unmatched: (count: number) => `${count} ${count === 1 ? "record has" : "records have"} no DOI or title, so ${count === 1 ? "it" : "they"} couldn't be checked for duplicates.`,
  removed: "Records removed before screening",
  duplicates: "Duplicate records removed",
  automation: "Records marked ineligible by automation tools",
  removedOther: "Records removed for other reasons",
  screening: "Screening and eligibility",
  screened: "Records screened",
  screenedExcluded: "Records excluded",
  sought: "Reports sought for retrieval",
  notRetrieved: "Reports not retrieved",
  assessed: "Reports assessed for eligibility",
  calculate: (value: number | null) => (value === null ? "Leave blank to calculate from the numbers above." : `Leave blank to calculate: ${value.toLocaleString("en-GB")}.`),
  reasons: "Reports excluded, with reasons",
  reasonLabel: "Reason",
  reasonCount: "Reports",
  addReason: "Add reason",
  addCommon: "Add a common reason",
  chooseReason: "Choose a reason",
  otherColumn: "Other methods",
  otherSought: "Reports sought for retrieval",
  otherNotRetrieved: "Reports not retrieved",
  otherAssessed: "Reports assessed for eligibility",
  otherReasons: "Reports excluded, with reasons",
  included: "Included",
  reportsIncluded: "Reports of included studies",
  studiesIncluded: "Studies included",
  studiesHint: "Several reports can describe one study.",
  fromMatrix: "Count included studies from a Literature Matrix export",
  fromMatrixIntro: "Paste the CSV exported from the Literature Matrix Builder with your included studies; the number of studies is filled in.",
  fromMatrixButton: "Count studies",

  checks: "Checks",
  checksClear: "Every number adds up.",
  problems: (count: number) => `${count} ${count === 1 ? "problem" : "problems"}`,
  warnings: (count: number) => `${count} ${count === 1 ? "point" : "points"} to check`,
  goTo: "Go to the field",

  appearance: "Appearance",
  orientation: "Orientation",
  theme: "Colours",
  typeface: "Typeface",
  fontSize: "Text size",
  points: (size: number) => `${size} pt`,
  wording: "Change the wording of boxes",
  wordingHint: "Leave a box blank to use the standard wording.",
  arrows: "Hide or label arrows",
  arrowShown: "Show",
  arrowLabel: "Label",
  arrowNames: {
    "identified-removed": "Identified → removed before screening",
    "identified-screened": "Identified → screened",
    "screened-excluded": "Screened → excluded",
    "screened-sought": "Screened → sought for retrieval",
    "sought-notRetrieved": "Sought → not retrieved",
    "sought-assessed": "Sought → assessed",
    "assessed-excluded": "Assessed → excluded",
    "assessed-included": "Assessed → included",
    "other-identified-sought": "Other methods: identified → sought",
    "other-sought-notRetrieved": "Other methods: sought → not retrieved",
    "other-sought-assessed": "Other methods: sought → assessed",
    "other-assessed-excluded": "Other methods: assessed → excluded",
    "other-assessed-included": "Other methods: assessed → included",
  } as Record<string, string>,
  labelNames: {
    identificationHeader: "Main heading",
    otherHeader: "Other methods heading",
    identified: "Records identified",
    removed: "Records removed",
    screened: "Records screened",
    screenedExcluded: "Records excluded",
    sought: "Reports sought",
    notRetrieved: "Reports not retrieved",
    assessed: "Reports assessed",
    reportsExcluded: "Reports excluded",
    otherIdentified: "Other methods: records identified",
    otherSought: "Other methods: reports sought",
    otherNotRetrieved: "Other methods: reports not retrieved",
    otherAssessed: "Other methods: reports assessed",
    otherExcluded: "Other methods: reports excluded",
    included: "Included",
    note: "Note below the diagram",
  } as Record<string, string>,

  result: "Your diagram",
  previewLabel: "Flow diagram preview",
  alt: "Text alternative",
  altHint: "Paste this into Word's or PowerPoint's Alt Text box.",
  copyAlt: "Copy text alternative",
  copiedAlt: "Copied text alternative",
  paragraph: "The flow in words",
  paragraphHint: "A paragraph to adapt for your methods or results section.",
  copyParagraph: "Copy paragraph",
  copiedParagraph: "Copied paragraph",
  table: "Table view",
  tableCaption: "Every number in the diagram",
  stage: "Stage",
  count: "n",
  source: "Source",
  entered: "Entered",
  calculated: "Calculated",
  export: "Export",
  exportIntro: "SVG and PDF stay sharp at any size, for Word, PowerPoint and journals. PNG is 300 DPI.",
  copyDiagram: "Copy diagram",
  download: (format: string) => `Download ${format}`,

  guide: "The diagram and its checks",
  guideIntro: "What each box reports, and the checks the builder runs.",
  guideBoxes: "The boxes",
  guideBoxItems: [
    "Records identified: everything the database and register searches returned, before removing duplicates.",
    "Records removed before screening: duplicates, records marked ineligible by automation tools, and records removed for other reasons.",
    "Records screened and excluded: titles and abstracts screened, and those excluded at that stage.",
    "Reports sought and not retrieved: full texts you tried to obtain, and those you couldn't.",
    "Reports assessed and excluded: full texts assessed for eligibility, and those excluded, with the number for each reason.",
    "Studies included: the studies in the review, and the reports that describe them. One study can have several reports.",
    "Other methods: records found by searching websites, organisations or citations, followed through the same stages in their own column.",
  ],
  guideChecks: "The checks",
  guideCheckItems: [
    "Numbers: every count is a whole number and none is negative.",
    "Missing values: the numbers the diagram needs, and those PRISMA 2020 asks for, such as reasons for exclusion.",
    "Arithmetic: each stage equals the one before it, less what was removed or excluded.",
    "Flow integrity: no box removes more than reached it, and there are no more studies than reports.",
    "Sequence: each stage is no larger than the one before.",
  ],
} as const;
