export const page = {
  title: "SPSS Research Lab",
  summary: "Connects a research question and selected analysis to IBM SPSS Statistics procedures, output tables, assumptions and reporting tools.",
  metaDescription: "Learn how to prepare data, run supported procedures in IBM SPSS Statistics, find the relevant output, check assumptions and continue to effect-size calculation and interpretation.",
  intro: "A practical workflow for the point when your data are ready: prepare and describe the data, use ResearchKit's test-selection reasoning, follow the matching IBM SPSS Statistics procedure, then check assumptions, effect size, output and reporting.",
  noScript: "The procedure reference and learning sections remain available without JavaScript. Project context and the procedure selector need JavaScript.",
  projectHeading: "From your research project",
  projectIntro: "When a workspace project is open, its question, variables, hypotheses and accepted analysis methods appear here. This Lab reads the project and does not change or save it.",
  noProject: "No workspace project is open. You can still use the procedure references below, or open your project workspace.",
  noQuestion: "No research question is recorded yet.",
  noVariables: "No variables are recorded yet.",
  noAnalyses: "No accepted analysis methods are recorded yet. The Lab does not infer a test here.",
  workflowHeading: "Your analysis workflow",
  procedureHeading: "SPSS procedure reference",
  procedureIntro: "Choose a procedure only after a statistical method has been selected. This selector opens a procedure reference; it does not recommend a statistical test.",
  procedureEmpty: "Select a supported method to review its IBM SPSS procedure.",
  practiceHeading: "Practice with a synthetic example",
  practiceIntro: "The Statistical Test Finder already includes deterministic teaching datasets. Pick an example to inspect its research question, data and matching SPSS procedure.",
  practiceLabel: "Worked example",
  linksHeading: "Continue in ResearchKit",
  installHeading: "Using IBM SPSS Statistics",
  installText: "ResearchKit does not provide or license SPSS. Obtain and activate IBM SPSS Statistics through IBM or your institution, following the current IBM installation and licensing guidance. The menu paths here are based on IBM SPSS Statistics 32 documentation and may differ in another version or licensed edition.",
  foundationsHeading: "Prepare and describe your data",
  foundations: [
    "Each row should represent the unit of analysis (often one participant); each column should represent one variable. Keep a codebook that records names, labels, values, units, measurement level and any recoding.",
    "Variable View stores metadata such as variable name, label, value labels, missing-value definitions and measurement level. Data View shows cases by rows and variables by columns. Categorical numeric codes are choices made for a particular study, not universal meanings.",
    "Check imported Excel or CSV data for header mistakes, duplicate cases, impossible values, missingness, range errors and outliers before analysis. Keep the original file unchanged and document every cleaning or reverse-coding decision.",
    "Start with frequencies for categorical variables and suitable summaries/plots for quantitative variables. A mean and SD are not appropriate summaries for every measurement level or distribution.",
    "Store the data file, syntax, output and a short decision log together. Syntax makes menu-driven choices reproducible; preserve the version that produced the reported tables.",
  ],
  outputHeading: "Read output, then interpret it",
  outputText: "Use the procedure card to find the table, row and value in SPSS. Record the statistic, degrees of freedom, p-value, confidence interval and effect-size measure where relevant. Then use the Results Interpretation Assistant for numerical and research-context interpretation; do not read significance from color or from p alone.",
  privacyHeading: "Privacy",
  privacy: "This Lab does not import, upload or store your SPSS data. A connected workspace remains in your browser under ResearchKit's workspace behavior.",
} as const;