/** All wording for the Conceptual Framework Builder. Academic content lives in the knowledge layer. */

export const page = {
  title: "Conceptual Framework Builder",
  /** One sentence, for listings such as the tools index. */
  summary: "Draws a conceptual framework figure from your variables and hypotheses, which you can edit and export as SVG, PNG or PDF.",
  metaDescription:
    "Create a conceptual framework figure from your own variables and hypotheses. Edit boxes and arrows, check alignment with your objectives, and export vector SVG, 300 DPI PNG or PDF.",
  intro:
    "Your variables and hypotheses become a conceptual framework figure, laid out automatically: independent variables on the left, dependent variables on the right, mediators and moderators between them. Edit anything, check how it fits your objectives, and export it for your thesis or paper.",
  noScript:
    "The Conceptual Framework Builder draws and edits the figure in your browser, which needs JavaScript. Turn on JavaScript to use it. The explanation below works without it.",
  howHeading: "How the builder works",
  layoutHeading: "How the figure is laid out",
  limitsHeading: "What this tool can't do",
  reviewHeading: "Awaiting review",
  privacyHeading: "Privacy",
  privacy: "Everything stays in your browser. Nothing is sent anywhere or saved, and exports are created on your device.",
} as const;

export const how: readonly string[] = [
  "The builder reads your project draft: variables, hypotheses, research question and objectives. Enter them in the first steps; later versions will bring them across from the other research tools.",
  "Every variable you list becomes a box. Relationships come only from your hypotheses: nothing is inferred, so a variable without a hypothesis appears unconnected until you connect it.",
  "You can add, rename, retype and delete variables and relationships, and move boxes with the mouse or the arrow keys. Warnings explain possible problems but never stop you editing.",
  "The builder writes only the conceptual framework section of your project draft, so later tools can use the same figure.",
];

export const layoutRules: readonly string[] = [
  "Independent variables sit in a column on the left, dependent variables in a column on the right.",
  "Moderators sit above the connector they moderate, with an arrow pointing at it. Mediators sit below, between the two columns.",
  "Control and extraneous variables sit in labelled groups at the bottom.",
  "Relationship labels, such as “H1 (+)”, sit on their connector. Line style shows the type of relationship: solid, dashed or dotted, with one, two or no arrowheads.",
];

export const steps = {
  project: "Project details",
  projectIntro: "Enter each variable exactly as you name it elsewhere, one per line.",
  example: "Load an example project",
  exampleLoaded: "Example project loaded. It is fictional, for trying the builder.",
  question: "Research question",
  objectives: "Research objectives",
  objectivesHint: "One per line. Relationships are checked against these.",
  independent: "Independent variables",
  dependent: "Dependent variables",
  mediator: "Mediators (optional)",
  moderator: "Moderators (optional)",
  control: "Control variables (optional)",
  population: "Population",
  populationHint: "Who the hypotheses are about.",
  location: "Location (optional)",
  timeContext: "Time frame (optional)",
  perLine: "One per line.",
  hypotheses: "Hypotheses",
  hypothesesIntro:
    "Relationships in the figure come from hypotheses. Until the tools share a saved project, draft them here with the Hypothesis Builder's rules; to edit their wording, use the Hypothesis Builder.",
  formLegend: "What do your hypotheses state?",
  forms: { difference: "Differences between groups", relationship: "Relationships between variables", prediction: "Predictions of an outcome" },
  directionLegend: "Direction",
  hypothesesCount: (count: number) => `${count} ${count === 1 ? "hypothesis" : "hypotheses"} in your project.`,
  noHypotheses: "Add at least one independent and one dependent variable to draft hypotheses.",
  figure: "Your framework",
  figureHint:
    "Select a box, then use the arrow keys to move it (hold Shift to move further), or drag it. Select a connector to see which hypothesis and objective it comes from.",
  diagramLabel: "Conceptual framework. Boxes and connectors can be selected.",
  moveHint: "Use the arrow keys to move it; hold Shift to move further.",
  connectorHint: "Press Enter to see where it comes from.",
  autoLayout: "Auto layout",
  resetLayout: "Reset layout",
  undo: "Undo",
  rebuild: "Rebuild from project details",
  rebuildConfirm: "This replaces your edits with a new figure built from your project details.",
  rebuildYes: "Rebuild and replace my edits",
  rebuildNo: "Keep my edits",
  edited: "You have edited the figure, so changes to your project details no longer update it.",
  appearance: "Appearance",
  colourLegend: "Colours",
  colour: "ResearchKit colours",
  monochrome: "Black and white",
  typesLegend: "Variable types in boxes",
  showTypes: "Show",
  hideTypes: "Hide",
  textDescription: "Text description of the figure",
  details: "Relationship details",
  noSelection: "Select a connector in the figure, or a relationship below, to see where it comes from.",
  createdBy: "Created from these hypotheses",
  addedByYou: "Added by you. No hypothesis in your project states it.",
  supportedBy: "Supported by these objectives",
  noObjective: "No objective mentions both variables.",
  moderates: "Moderates",
  variables: "Variables",
  variableName: (name: string) => `Name of ${name}`,
  variableType: (name: string) => `Type of ${name}`,
  deleteVariable: (name: string) => `Delete ${name}`,
  newVariable: "New variable",
  newVariableType: "Type",
  addVariable: "Add variable",
  relationships: "Relationships",
  noRelationships: "No relationships yet. Add one below, or add hypotheses above.",
  relationshipType: (description: string) => `Type of relationship: ${description}`,
  relationshipLabel: (description: string) => `Label for: ${description}`,
  showDetails: "Show details",
  deleteRelationship: "Delete",
  newRelationship: "Add a relationship",
  from: "From",
  to: "To",
  type: "Type",
  moderatesField: "Connector it moderates",
  noModerated: "The target variable itself",
  label: "Label (optional)",
  addRelationship: "Add relationship",
  choose: "Choose",
  warnings: "Warnings",
  noWarnings: "No warnings. The figure matches your hypotheses and objectives.",
  warningTag: "Warning",
  why: "Why:",
  export: "Export",
  exportIntro:
    "SVG and PDF are vector formats that stay sharp at any size. PNG is exported at 300 DPI. “Copy figure” puts the figure on the clipboard as SVG and PNG for pasting into documents.",
  copyFigure: "Copy figure",
  copySvgSubject: "SVG code",
  downloadSvg: "Download SVG",
  downloadPng: "Download PNG (300 DPI)",
  downloadPdf: "Download PDF",
  figureTitle: "Conceptual framework",
  projectDraft: "Your project draft",
  projectDraftIntro: "This tool writes only the Conceptual framework section. Everything else is shown as you entered it.",
} as const;
