/** All wording for the Research Chart Builder. Academic content lives in the knowledge layer. */

export const page = {
  title: "Research Chart Builder",
  /** One sentence, for listings such as the tools index. */
  summary: "Turns your data into publication-ready charts for theses, journals and reports, with APA- and IEEE-friendly styles, text alternatives and sharp exports.",
  metaDescription:
    "Make publication-ready bar, line, pie, histogram, scatter, box plot, Likert and 15 more chart types from pasted data. APA- and IEEE-friendly styles, grayscale with patterns, alt text, and 300 DPI PNG, SVG and PDF export.",
  intro:
    "Paste or type your data, choose a chart, and export a figure that stays sharp in Word and journals. The builder suggests charts that suit your variables and analyses, writes a text alternative and table for every chart, and never relies on colour alone.",
  noScript:
    "Drawing charts needs JavaScript. Turn on JavaScript to use the builder. The guide to every chart type below works without it.",
  howHeading: "How the builder works",
  limitsHeading: "What this tool can't do",
  reviewHeading: "Awaiting review",
  privacyHeading: "Privacy",
  privacy: "Your data stays in your browser. Nothing is sent anywhere or saved, and it is cleared when you leave the page.",
} as const;

export const how: readonly string[] = [
  "Paste a table from a spreadsheet, or type or paste comma-, tab- or semicolon-separated values. The first row is read as column names when it has no numbers.",
  "Choose a chart type, or let the builder suggest one: from what the chart should show, or from your project's variables, measurement levels, objectives and planned analyses.",
  "Set titles, style, colours and labels. APA- and IEEE-friendly styles move the title to a caption for your document, set fonts, and choose gridlines; grayscale adds patterns so print never depends on colour.",
  "The chart is checked as you go. Problems that stop it being drawn, and choices readers may find misleading, are explained with how to fix them.",
  "Export as SVG or PDF, which stay sharp at any size, or as a 300 DPI PNG. Copy the chart straight into your document, with its alt text and caption.",
];

export const steps = {
  data: "Your data",
  dataIntro: "Paste a table from Excel, Google Sheets or SPSS, or type values separated by commas. Put category names or labels in the first column.",
  dataLabel: "Data table",
  dataHint: (layout: string) => `For this chart: ${layout}`,
  loadExample: "Load example data",
  exampleNote: "Example data is fictional, for trying the builder.",
  exampleSubtitle: "Fictional example data",
  readAs: (rows: number, columns: number, delimiter: string, header: boolean) =>
    `Read ${rows} ${rows === 1 ? "row" : "rows"} and ${columns} ${columns === 1 ? "column" : "columns"}, separated by ${delimiter}${header ? ", with column names from the first row" : ", with no column names"}.`,
  delimiters: { ",": "commas", "\t": "tabs", ";": "semicolons (with decimal commas)" } as Record<string, string>,
  checkData: "Check how the data was read",
  columnKind: { number: "numbers", text: "text" } as Record<string, string>,
  previewCaption: (shown: number, total: number) => (shown < total ? `The first ${shown} of ${total} rows, as read` : "Your data, as read"),
  missing: "missing",
  fits: "Chart types this data fits",

  chart: "Chart type",
  chartIntro: "Choose the chart, or start from a suggestion below.",
  chartLabel: "Chart type",
  bestFor: "Best for",
  suggestHeading: "Suggestions",
  purposeLabel: "What should the chart show?",
  purposeEmpty: "Choose a purpose",
  // Names keep their capitals, as in “Likert scale chart”.
  useChart: (label: string) => `Use ${label}`,
  projectToggle: "Suggestions from your project",
  projectIntro: "Enter what you already know about your research. Charts are suggested for each variable, for each predictor and outcome, for your planned analyses and for your objectives. Nothing here needs to be complete.",
  exampleProject: "Load an example project",
  exampleProjectLoaded: "Example project loaded. It is fictional, for trying the builder.",
  projectVariables: "Each variable",
  projectPairs: "Predictors and outcomes",
  projectAnalyses: "Your planned analyses",
  projectObjectives: "Your objectives",
  projectNothing: "Add variables and their measurement levels to see suggestions.",
  basedOn: "Based on",
  suggestedTitles: (title: string, x: string, y: string) => [title && `title “${title}”`, x && `x axis “${x}”`, y && `y axis “${y}”`].filter(Boolean).join(", "),
  titlesNote: "Using it also sets",

  appearance: "Titles and style",
  title: "Title",
  titleHint: "In APA and IEEE styles, the title goes in your document's caption, not the image.",
  subtitle: "Subtitle",
  xTitle: "X-axis title",
  yTitle: "Y-axis title",
  axisHint: "Leave blank to use the column name.",
  style: "Style",
  palette: "Colours",
  fontSize: "Font size",
  fontSizeHint: "Points at the chosen figure size. Journals usually ask for at least 8 points.",
  points: (size: number) => `${size} pt`,
  size: "Figure size",
  sizeHint: "Draw at the size it will appear, so text prints at its set size.",
  more: "Labels, axes and order",
  legend: "Legend",
  legendOptions: { auto: "Automatic (two or more series)", show: "Show", hide: "Hide" } as Record<string, string>,
  dataLabels: "Data labels",
  percentages: "Values or percentages",
  percentageOptions: { values: "Values", percentages: "Percentages" } as Record<string, string>,
  gridlines: "Gridlines",
  onOff: { on: "On", off: "Off" } as Record<string, string>,
  axisDecimals: "Axis decimal places",
  labelDecimals: "Label decimal places",
  auto: "Automatic",
  rotate: "Category labels",
  rotateOptions: { "0": "Horizontal (rotated if crowded)", "45": "Rotated 45°", "90": "Rotated 90°" } as Record<string, string>,
  sort: "Order",
  sortOptions: { none: "As entered", descending: "Largest first", ascending: "Smallest first" } as Record<string, string>,
  sortHint: "Some charts keep the data's own order, because it carries meaning.",

  result: "Your chart",
  empty: "Enter or paste data above, or load the example, to see your chart.",
  cannotDraw: "The chart can't be drawn yet",
  problemTag: "Problem",
  warningTag: "Check",
  figureLabel: "Chart preview",
  caption: "Caption for your document",
  captionHint: "Number figures in the order they appear in your text.",
  notes: "Adjustments",
  summary: "Summary",
  alt: "Alt text",
  altHint: "Paste this into Word's Alt Text box, or your journal's figure description.",
  table: "Table view",
  tableHint: "The numbers the chart shows, for readers who can't see it and for checking.",
  export: "Export",
  exportIntro: "SVG and PDF stay sharp at any size and are best for Word and journals. PNG is 300 DPI, the resolution journals commonly require.",
  copyChart: "Copy chart",
  downloadPng: "Download PNG (300 DPI)",
  downloadSvg: "Download SVG",
  downloadPdf: "Download PDF",
  copyAlt: "Copy alt text",
  copiedAlt: "Copied alt text",
  copyCaption: "Copy caption",
  copiedCaption: "Copied caption",
  copyTable: "Copy data as CSV",
  copiedTable: "Copied data",

  guide: "Chart types",
  guideIntro: "Every chart the builder draws: what it shows, when to use it, and how to lay out its data. Recommendations follow common guidance for statistical graphics; references will be added after academic review.",
  contents: "Charts",
  whenToUse: "When to use it",
  layout: "Data layout",
  example: "Example data",
} as const;
