export { CHART_TYPES, CHART_TYPE_INFO, DEFAULT_OPTIONS, FIGURE_SIZES, LABEL_ROTATIONS, PALETTES, SORT_ORDERS, STYLE_PRESETS, getChartType, type ChartOptions, type ChartType, type ChartTypeInfo, type DataShape, type FigureSizeId, type LabelRotation, type PaletteId, type SortOrder, type StylePreset } from "./types";
export { MAX_ROWS, parseTable, tableToCsv, type Cell, type Column, type DataTable, type ParseResult } from "./table";
export { chartData, type ChartData } from "./data";
export { MAX_PIE_PARTS, MAX_SERIES, canDraw, chartIssues, fittingTypes, type ChartIssue } from "./validate";
export { FONT_SIZES, STYLES, applyStyle, figureCaption, paletteLabel, type StyleSpec } from "./style";
export { renderChart, type RenderResult } from "./render";
export { describeChart, type ChartText, type TableView } from "./describe";
export { CHART_PNG_DPI, PX_TO_PT, chartFileName, pngPixels, sceneToPdf, sceneToSvg } from "./export";
export type { Scene, SceneItem } from "./scene";
export { CHART_PURPOSES, CHART_PURPOSE_INFO, MAX_PAIRS, chartsForLevel, chartsForMeasure, chartsForMethod, chartsForPair, chartsForPurpose, mergeSuggestions, noChartReason, purposesInText, recommendationsForProject, type ChartPurpose, type ChartSuggestion, type ProjectChartGroup, type ProjectChartPlan } from "./recommend";
export { CHART_LIMITATIONS, CHART_REVIEW_ITEMS } from "./limits";
