/**
 * Statistical assumptions, each defined once and shared by every method that relies
 * on it: what it requires, why it matters, how researchers usually check it, the
 * thresholds commonly used, what a violation does, and what to do instead. Standard
 * textbook guidance awaiting review by a statistician; thresholds are conventions,
 * not laws, and their sources will be added after review.
 */

export const ASSUMPTION_IDS = [
  "numeric-measurement",
  "ordinal-measurement",
  "categorical-variables",
  "binary-outcome",
  "independence",
  "paired-observations",
  "normality",
  "normality-of-residuals",
  "normality-of-differences",
  "multivariate-normality",
  "linearity",
  "monotonicity",
  "homoscedasticity",
  "homogeneity-of-variance",
  "homogeneity-of-covariance",
  "sphericity",
  "independent-errors",
  "multicollinearity",
  "outliers",
  "multivariate-outliers",
  "homogeneity-of-slopes",
  "covariate-independence",
  "linearity-of-logit",
  "events-per-predictor",
  "expected-counts",
  "group-sizes",
  "related-outcomes",
  "factorability",
  "factor-sample-size",
  "model-identification",
  "sem-sample-size",
  "measurement-model-quality",
  "discriminant-validity",
  "structural-collinearity",
  "distribution-shape",
] as const;
export type AssumptionId = (typeof ASSUMPTION_IDS)[number];

export interface Assumption {
  id: AssumptionId;
  name: string;
  /** What the assumption requires, in one sentence. */
  statement: string;
  /** Why it matters for the results. */
  why: string;
  /** How researchers usually check it: tests, plots and inspections. */
  howToCheck: readonly string[];
  /** Commonly used thresholds, each as a sentence. Conventions, not laws. */
  thresholds: readonly string[];
  /** What happens to the results if it doesn't hold. */
  ifViolated: string;
  /** What researchers commonly do instead. */
  remedies: readonly string[];
  /** Whether it can be judged before data are collected, from the project's design. */
  checkableFromDesign: boolean;
  /** Reference ids, empty until academic review. */
  references: readonly string[];
}

const assumption = (id: AssumptionId, name: string, statement: string, why: string, howToCheck: readonly string[], thresholds: readonly string[], ifViolated: string, remedies: readonly string[], checkableFromDesign = false): Assumption => ({
  id,
  name,
  statement,
  why,
  howToCheck,
  thresholds,
  ifViolated,
  remedies,
  checkableFromDesign,
  references: [],
});

export const ASSUMPTIONS: Readonly<Record<AssumptionId, Assumption>> = {
  "numeric-measurement": assumption(
    "numeric-measurement",
    "Interval or ratio measurement",
    "The outcome is measured on a numeric scale with equal intervals between values.",
    "Means, standard deviations and the tests built on them assume the distance between 3 and 4 equals the distance between 4 and 5.",
    ["Check how each variable was measured: its measurement level and response format.", "For scale scores made from several rating items, state that the total or average is treated as interval."],
    ["No numeric threshold: it is a question of measurement design.", "Single rating items are ordinal; scale scores from several items are commonly treated as interval, which should be stated."],
    "Means and tests can mislead when categories aren't evenly spaced.",
    ["Use a rank-based (non-parametric) test.", "Combine several rating items into a scale score, and report its reliability."],
    true,
  ),
  "ordinal-measurement": assumption(
    "ordinal-measurement",
    "At least ordinal measurement",
    "Values can be put in a meaningful order.",
    "Rank-based methods compare orders; unordered categories have no order to compare.",
    ["Check each variable's measurement level."],
    ["No numeric threshold: ordinal, interval and ratio variables all qualify."],
    "Ranks of unordered categories are meaningless.",
    ["For unordered categories, use a test for categorical data, such as chi-square."],
    true,
  ),
  "categorical-variables": assumption(
    "categorical-variables",
    "Categorical variables",
    "Both variables are measured in categories.",
    "The chi-square test compares counts in the cells of a table; it needs categories to count.",
    ["Check each variable's measurement level and answer options."],
    ["Categories should be mutually exclusive: each participant falls in exactly one."],
    "Numeric variables cut into categories lose information, and the cut-points can change the result.",
    ["Keep numeric variables numeric and use correlation, regression or a t-test instead."],
    true,
  ),
  "binary-outcome": assumption(
    "binary-outcome",
    "A two-category outcome",
    "The outcome has exactly two categories, such as yes and no.",
    "Binary logistic regression models the chance of one of two outcomes.",
    ["Check the outcome's categories."],
    ["Exactly two mutually exclusive categories."],
    "An outcome with more categories doesn't fit binary logistic regression.",
    ["Combine categories into two, if theory supports it.", "Use multinomial or ordinal logistic regression for three or more categories."],
    true,
  ),
  independence: assumption(
    "independence",
    "Independence of observations",
    "Each participant's data are unrelated to every other participant's, and each participant contributes once.",
    "Tests assume every observation adds new information. Related observations make standard errors too small and p-values too low.",
    ["Check the design: are any participants measured more than once, or grouped in ways that make them alike, such as classes or families?", "Check the sampling technique: cluster sampling groups participants."],
    ["No numeric threshold: it follows from the design and data collection."],
    "Violations inflate the chance of a false positive, often seriously.",
    ["Use paired or repeated measures methods when the same people are measured more than once.", "Use multilevel models, or adjust for clustering, when participants are grouped."],
    true,
  ),
  "paired-observations": assumption(
    "paired-observations",
    "Paired observations",
    "Each measurement in one condition is matched to one in the other, usually the same participant measured twice.",
    "Paired tests analyse the difference within each pair, which removes differences between people.",
    ["Check the design: are the same participants, or matched pairs, measured in both conditions?"],
    ["Every participant has a measurement at both times or in both conditions."],
    "Treating independent groups as paired, or paired data as independent, gives the wrong standard error.",
    ["Use the independent-samples version for separate groups.", "Use repeated measures methods for three or more times."],
    true,
  ),
  normality: assumption(
    "normality",
    "Normality",
    "The outcome is approximately normally distributed within each group.",
    "Parametric tests use the normal distribution to judge how surprising a result is; strong non-normality, especially in small samples, makes p-values inaccurate.",
    ["Inspect histograms and Q–Q plots for each group.", "Check skewness and kurtosis.", "Run the Shapiro–Wilk test, bearing in mind its power depends on sample size."],
    ["Shapiro–Wilk p above .05 is consistent with normality; with large samples it flags trivial departures, so rely on plots.", "Skewness and kurtosis between −2 and +2 are often treated as acceptable; some researchers use −1 to +1."],
    "With small samples, p-values and confidence intervals can be wrong. With larger samples, tests of means are commonly considered robust to moderate non-normality.",
    ["Use the non-parametric alternative.", "Transform the variable, such as a log transformation for right skew, and report it.", "Use bootstrapped confidence intervals."],
  ),
  "normality-of-residuals": assumption(
    "normality-of-residuals",
    "Normally distributed residuals",
    "The residuals (the differences between observed and predicted values) are approximately normal.",
    "Regression's significance tests and confidence intervals assume normal residuals; the predictors themselves needn't be normal.",
    ["Inspect a histogram and a normal P–P or Q–Q plot of the standardised residuals.", "Run the Shapiro–Wilk test on the residuals."],
    ["Standardised residuals should roughly follow the diagonal of the P–P plot.", "Shapiro–Wilk p above .05 is consistent with normal residuals; with large samples, rely on plots."],
    "Coefficients stay unbiased, but p-values and confidence intervals can be inaccurate, especially in small samples.",
    ["Use bootstrapped confidence intervals.", "Transform the outcome.", "Use robust regression."],
  ),
  "normality-of-differences": assumption(
    "normality-of-differences",
    "Normally distributed differences",
    "The differences between each pair of measurements are approximately normal.",
    "The paired t-test is a one-sample test of the differences, so it is their distribution that matters, not each measurement's.",
    ["Compute each participant's difference and inspect its histogram and Q–Q plot.", "Run the Shapiro–Wilk test on the differences."],
    ["Shapiro–Wilk p above .05 on the differences is consistent with normality.", "Skewness and kurtosis of the differences between −2 and +2 are often treated as acceptable."],
    "With few pairs, p-values can be inaccurate.",
    ["Use the Wilcoxon signed-rank test.", "Use a bootstrapped confidence interval for the mean difference."],
  ),
  "multivariate-normality": assumption(
    "multivariate-normality",
    "Multivariate normality",
    "The variables are jointly normally distributed, not just each one on its own.",
    "MANOVA and maximum likelihood SEM rely on it for their test statistics and standard errors.",
    ["Check each variable's normality first.", "Use Mardia's test of multivariate skewness and kurtosis.", "Check for multivariate outliers with Mahalanobis distance."],
    ["Mardia's coefficients non-significant, or a normalised multivariate kurtosis below about 5, are commonly treated as acceptable."],
    "Chi-square tests of fit become too large and standard errors too small, so models look worse and effects look stronger than they are.",
    ["Use robust estimation, such as maximum likelihood with Satorra–Bentler correction.", "Use bootstrapping.", "In MANOVA, report Pillai's trace, which is the most robust statistic."],
  ),
  linearity: assumption(
    "linearity",
    "Linearity",
    "The relationship between the variables is a straight line.",
    "Pearson correlation and linear regression measure straight-line relationships; a curved one is underestimated or missed.",
    ["Inspect a scatterplot of each pair.", "In regression, plot residuals against predicted values: they should scatter evenly around zero with no curve."],
    ["No numeric threshold: judge the plots.", "A clear curve in the residual plot means the relationship isn't linear."],
    "The strength of the relationship is underestimated, and predictions are wrong in parts of the range.",
    ["Add a squared term, or transform a variable.", "Use Spearman's correlation for a relationship that is monotonic but curved."],
  ),
  monotonicity: assumption(
    "monotonicity",
    "A monotonic relationship",
    "As one variable increases, the other consistently increases, or consistently decreases.",
    "Spearman's rho measures how consistently the ranks rise or fall together; a U-shaped relationship can give a rho near zero.",
    ["Inspect a scatterplot of the two variables."],
    ["No numeric threshold: judge the plot for a consistent direction."],
    "A relationship that rises then falls is missed.",
    ["Describe the relationship in parts of the range, or model the curve directly."],
  ),
  homoscedasticity: assumption(
    "homoscedasticity",
    "Homoscedasticity",
    "The spread of the residuals is the same at every level of the predicted values.",
    "Standard errors assume equal spread; unequal spread makes some coefficients look more or less precise than they are.",
    ["Plot standardised residuals against standardised predicted values: the band should have the same width throughout.", "Use the Breusch–Pagan or White test."],
    ["Breusch–Pagan p above .05 is consistent with equal spread.", "A funnel shape in the residual plot suggests unequal spread."],
    "Coefficients stay unbiased, but their standard errors and p-values are wrong.",
    ["Use heteroscedasticity-consistent (robust) standard errors.", "Transform the outcome.", "Use weighted least squares."],
  ),
  "homogeneity-of-variance": assumption(
    "homogeneity-of-variance",
    "Homogeneity of variance",
    "The groups being compared have similar variances.",
    "Tests that pool the groups' variances give the wrong answer when one group varies much more than another, especially with unequal group sizes.",
    ["Run Levene's test.", "Compare the largest and smallest group variances."],
    ["Levene's p above .05 is consistent with equal variances.", "A ratio of largest to smallest variance below about 2 to 3 is a common rule of thumb, especially when groups are similar in size."],
    "p-values become inaccurate, particularly when the smaller group has the larger variance.",
    ["Use Welch's t-test, or Welch's ANOVA with Games–Howell post hoc tests.", "Report Levene's test and the correction used."],
  ),
  "homogeneity-of-covariance": assumption(
    "homogeneity-of-covariance",
    "Homogeneity of covariance matrices",
    "The groups have similar variances and similar relationships between the outcomes.",
    "MANOVA pools the groups' covariance matrices; very different matrices distort its test.",
    ["Run Box's M test."],
    ["Box's M is very sensitive, so a strict level is commonly used: p above .001 is treated as acceptable."],
    "The multivariate test becomes inaccurate, especially with unequal group sizes.",
    ["Report Pillai's trace, which is the most robust multivariate statistic.", "Keep group sizes equal where possible."],
  ),
  sphericity: assumption(
    "sphericity",
    "Sphericity",
    "The variances of the differences between every pair of time points are similar.",
    "Repeated measures ANOVA's F test assumes it; when it fails, F is too large and false positives increase.",
    ["Run Mauchly's test.", "Look at the Greenhouse–Geisser epsilon."],
    ["Mauchly's p above .05 is consistent with sphericity; it only applies with three or more time points.", "If sphericity fails, use the Greenhouse–Geisser correction when epsilon is below about .75, and Huynh–Feldt when it is above."],
    "The F test is too liberal: it finds effects that aren't there more often than the stated level.",
    ["Apply the Greenhouse–Geisser or Huynh–Feldt correction.", "Use a multivariate approach or a linear mixed model."],
  ),
  "independent-errors": assumption(
    "independent-errors",
    "Independent errors",
    "The residuals of any two observations are unrelated, such as over time or in the order data were collected.",
    "Related residuals make standard errors too small.",
    ["Run the Durbin–Watson test.", "Plot residuals in the order the data were collected."],
    ["Durbin–Watson values near 2 suggest no autocorrelation; values between about 1.5 and 2.5 are commonly treated as acceptable."],
    "Significance tests become too liberal.",
    ["Model the time order, such as with time-series or multilevel methods."],
  ),
  multicollinearity: assumption(
    "multicollinearity",
    "No multicollinearity",
    "The predictors aren't too highly correlated with each other.",
    "Overlapping predictors compete to explain the same variation, so their individual coefficients become unstable and hard to interpret.",
    ["Inspect correlations between predictors.", "Check the variance inflation factor (VIF) and tolerance for each predictor."],
    ["A VIF below 10 (tolerance above .10) is a commonly used lenient cut-off; below 5 (tolerance above .20) is stricter.", "Correlations between predictors above about .80 to .90 are a warning sign."],
    "Coefficients and their signs can change unpredictably, and important predictors can look non-significant.",
    ["Remove or combine overlapping predictors, if theory allows.", "Centre variables before creating interaction terms."],
  ),
  outliers: assumption(
    "outliers",
    "No influential outliers",
    "No single case distorts the result.",
    "Means, correlations and regression lines are pulled towards extreme values, so one case can change a conclusion.",
    ["Inspect boxplots and scatterplots.", "Check standardised residuals and Cook's distance in regression."],
    ["Standardised scores or residuals beyond ±3 are commonly flagged; beyond ±2.5 in small samples.", "Cook's distance above 1 suggests an influential case; some use 4 divided by N."],
    "Estimates and p-values can depend on one or two cases.",
    ["Check whether the value is an error, and correct it if so.", "Report the analysis with and without the case.", "Use a rank-based or robust method."],
  ),
  "multivariate-outliers": assumption(
    "multivariate-outliers",
    "No multivariate outliers",
    "No case has an unusual combination of values across several variables.",
    "A case can look ordinary on each variable but unusual in combination, and still distort multivariate results.",
    ["Compute Mahalanobis distance for each case."],
    ["A Mahalanobis distance beyond the chi-square critical value at p < .001, with degrees of freedom equal to the number of variables, is commonly flagged."],
    "Multivariate estimates and fit statistics can be distorted.",
    ["Check the case for errors.", "Report results with and without it."],
  ),
  "homogeneity-of-slopes": assumption(
    "homogeneity-of-slopes",
    "Homogeneity of regression slopes",
    "The covariate relates to the outcome in the same way in every group.",
    "ANCOVA adjusts every group by one common slope; if the slopes differ, the adjustment is wrong for some groups.",
    ["Add a group × covariate interaction to the model and test it."],
    ["A non-significant interaction (p above .05) is consistent with equal slopes."],
    "The adjusted group means can mislead, because the group difference depends on the covariate's value.",
    ["Report the interaction instead, using regression with the interaction term.", "Describe the group difference at different covariate values."],
  ),
  "covariate-independence": assumption(
    "covariate-independence",
    "Covariate independent of the grouping",
    "The covariate isn't affected by group membership, usually because it is measured before the intervention.",
    "Adjusting for a covariate that the groups themselves changed can remove part of the effect being tested.",
    ["Check when the covariate was measured.", "Compare the covariate across groups: in a randomised design, differences should be small."],
    ["No numeric threshold: it follows from the design and timing of measurement."],
    "The adjusted effect can be biased, towards zero or away from it.",
    ["Measure covariates before the intervention.", "Don't adjust for variables the treatment may change."],
    true,
  ),
  "linearity-of-logit": assumption(
    "linearity-of-logit",
    "Linearity of the logit",
    "Each numeric predictor has a straight-line relationship with the log odds of the outcome.",
    "Logistic regression models the log odds as a straight line in each numeric predictor; a curved relationship is misrepresented.",
    ["Use the Box–Tidwell test: add each numeric predictor multiplied by its natural log, and test those terms."],
    ["Non-significant Box–Tidwell terms are consistent with linearity; a Bonferroni-corrected level is often used."],
    "Odds ratios for the affected predictor are misleading.",
    ["Transform the predictor, or group it into categories if theory supports it."],
  ),
  "events-per-predictor": assumption(
    "events-per-predictor",
    "Enough cases per predictor",
    "The smaller outcome group has enough cases for the number of predictors.",
    "With few cases in the smaller group, estimates become unstable or can't be computed.",
    ["Count the cases in the smaller outcome category and divide by the number of predictors."],
    ["A common rule of thumb is at least 10 cases in the smaller outcome group per predictor; it is debated and some recommend more."],
    "Odds ratios can be very large with very wide confidence intervals, or the model may fail to converge.",
    ["Use fewer predictors.", "Use penalised (Firth) logistic regression."],
  ),
  "expected-counts": assumption(
    "expected-counts",
    "Adequate expected counts",
    "The counts expected in each cell, if the variables were unrelated, are large enough.",
    "The chi-square test is an approximation that is poor when expected counts are small.",
    ["Look at the expected counts in your software's output."],
    ["At least 80% of cells should have expected counts of 5 or more, and none below 1.", "For a 2 × 2 table, every expected count should be 5 or more."],
    "The p-value can be inaccurate.",
    ["Use Fisher's exact test.", "Combine categories with few cases, if theory supports it."],
  ),
  "group-sizes": assumption(
    "group-sizes",
    "Adequate group sizes",
    "Each group, or combination of groups, has enough participants.",
    "Small or very unequal groups make tests less robust to other violations, and make some effects impossible to estimate.",
    ["Count the participants in every group or cell."],
    ["Roughly equal groups make most tests more robust.", "In MANOVA, each cell should have more cases than there are outcome variables."],
    "Tests become sensitive to unequal variances, and power falls.",
    ["Plan equal groups where possible.", "Use Welch-type corrections, or combine small groups if theory allows."],
  ),
  "related-outcomes": assumption(
    "related-outcomes",
    "Moderately related outcomes",
    "The outcome variables are related to each other, but not so strongly that they measure the same thing.",
    "MANOVA gains from analysing related outcomes together; unrelated outcomes are better analysed separately, and near-identical ones are redundant.",
    ["Inspect the correlations between the outcome variables."],
    ["Moderate correlations are ideal; correlations above about .80 to .90 suggest redundancy."],
    "With unrelated outcomes MANOVA loses power; with near-identical ones it becomes unstable.",
    ["Analyse unrelated outcomes with separate ANOVAs and a corrected significance level.", "Combine near-identical outcomes."],
  ),
  factorability: assumption(
    "factorability",
    "Factorability",
    "The items share enough common variance for factors to be meaningful.",
    "Factor analysis looks for groups of correlated items; if items are barely correlated, any factors found are unstable.",
    ["Check the Kaiser–Meyer–Olkin (KMO) measure.", "Run Bartlett's test of sphericity.", "Inspect the correlation matrix."],
    ["KMO of .60 or more is commonly required; Kaiser treated .50 as the minimum.", "Bartlett's test should be significant (p below .05).", "Many correlations between items should be above about .30."],
    "Factors may be unstable or uninterpretable.",
    ["Remove items with low correlations or low individual KMO values.", "Collect more data."],
  ),
  "factor-sample-size": assumption(
    "factor-sample-size",
    "Adequate sample for factor analysis",
    "There are enough participants for a stable factor solution.",
    "Correlations, and so factors, are unstable in small samples.",
    ["Compare the sample size with the number of items and the strength of the loadings."],
    ["Common guidance ranges from at least 100 participants to 300 or more.", "A ratio of 5 to 10 participants per item is often cited; strong loadings allow smaller samples."],
    "Factors may not replicate in another sample.",
    ["Collect more data.", "Use fewer items.", "Rely on established measures' published structure."],
    true,
  ),
  "model-identification": assumption(
    "model-identification",
    "Model identification",
    "The model has enough information to estimate every parameter.",
    "An unidentified model has no unique solution, so its estimates are meaningless.",
    ["Check that degrees of freedom are zero or more.", "Check each latent construct has enough indicators."],
    ["Each latent construct commonly needs at least three indicators, or two with constraints.", "The model's degrees of freedom must be zero or positive."],
    "The software fails to estimate the model, or gives meaningless estimates.",
    ["Add indicators.", "Fix or constrain parameters as theory allows."],
    true,
  ),
  "sem-sample-size": assumption(
    "sem-sample-size",
    "Adequate sample for SEM",
    "There are enough participants for the model's complexity.",
    "CB-SEM relies on large-sample theory; small samples give unstable estimates, poor fit and failed estimation.",
    ["Compare the sample with the number of estimated parameters."],
    ["200 or more is a commonly cited minimum for CB-SEM; ratios of 5 to 10 participants per estimated parameter are also used.", "For PLS-SEM, a common minimum is ten times the largest number of arrows pointing at one construct; power analysis is preferred."],
    "Estimates are unstable, fit statistics are unreliable, and the model may not converge.",
    ["Simplify the model.", "Use PLS-SEM for smaller samples, if its approach suits your aims."],
    true,
  ),
  "measurement-model-quality": assumption(
    "measurement-model-quality",
    "A reliable and valid measurement model",
    "Each construct's indicators load strongly on it, reliably and with convergent validity.",
    "Paths between constructs are only as trustworthy as the measurement of the constructs.",
    ["Check indicator loadings.", "Check composite reliability and average variance extracted (AVE)."],
    ["Indicator loadings of .70 or more are commonly sought; .40 to .70 may be kept if reliability and AVE are adequate.", "Composite reliability between .70 and .95.", "AVE of .50 or more."],
    "Weak measurement weakens and biases the paths between constructs.",
    ["Remove weak indicators if content validity allows.", "Revise the measure before the main study."],
  ),
  "discriminant-validity": assumption(
    "discriminant-validity",
    "Discriminant validity",
    "Each construct is distinct from the others.",
    "If two constructs are indistinguishable, paths between them are meaningless.",
    ["Check the heterotrait–monotrait ratio (HTMT).", "Compare each construct's square root of AVE with its correlations (Fornell–Larcker criterion)."],
    ["HTMT below .85 is strict; below .90 is commonly accepted for conceptually similar constructs.", "Each construct's square root of AVE should exceed its correlations with the others."],
    "Constructs may be measuring the same thing, so relationships between them are inflated.",
    ["Revise overlapping items.", "Merge constructs if theory supports it."],
  ),
  "structural-collinearity": assumption(
    "structural-collinearity",
    "No collinearity between predictor constructs",
    "Constructs predicting the same outcome aren't too highly correlated.",
    "Overlapping predictor constructs make path coefficients unstable.",
    ["Check the variance inflation factor (VIF) of predictor constructs in the structural model."],
    ["VIF below 3 is ideal in PLS-SEM guidance; below 5 is commonly accepted."],
    "Path coefficients can be biased or change sign.",
    ["Merge or remove overlapping constructs, if theory allows.", "Create a higher-order construct."],
  ),
  "distribution-shape": assumption(
    "distribution-shape",
    "Summaries that match the distribution",
    "Each summary suits the variable's measurement level and shape.",
    "A mean describes a symmetric numeric variable well but misleads for skewed data or single ordinal items.",
    ["Inspect a histogram or bar chart of each variable.", "Compare the mean with the median."],
    ["Report the mean and standard deviation for roughly symmetric numeric variables, and the median and interquartile range for skewed or ordinal ones."],
    "Readers get a misleading picture of what is typical.",
    ["Report the median and interquartile range.", "Report frequencies and percentages for categories."],
  ),
};

export function getAssumption(id: AssumptionId): Assumption {
  const found = ASSUMPTIONS[id];
  if (!found) throw new RangeError(`Unknown assumption: ${id}`);
  return found;
}
