/**
 * Research designs: what each is, when it is used, and the traits the compatibility
 * checks and decision assistant compare. Standard textbook content awaiting review by
 * a methodology specialist. References are left empty until chosen at review.
 *
 * Some entries describe different dimensions of a design: “cross-sectional” and
 * “longitudinal” describe timing, and “descriptive”, “explanatory” and “exploratory”
 * describe purpose. A study can combine one of each with a strategy such as a survey.
 */

import type { LayerId } from "./types";

export const DESIGN_IDS = [
  "experimental",
  "true-experimental",
  "quasi-experimental",
  "pre-experimental",
  "survey",
  "case-study",
  "phenomenology",
  "grounded-theory",
  "ethnography",
  "narrative-inquiry",
  "action-research",
  "historical",
  "correlational",
  "cross-sectional",
  "longitudinal",
  "descriptive",
  "explanatory",
  "exploratory",
  "sequential-mixed",
  "concurrent-mixed",
  "embedded-mixed",
] as const;
export type DesignId = (typeof DESIGN_IDS)[number];

export type DesignFamily = "experimental" | "non-experimental" | "qualitative" | "mixed" | "timing" | "purpose";

export const DESIGN_FAMILY_LABELS: Readonly<Record<DesignFamily, string>> = {
  experimental: "Experimental designs",
  "non-experimental": "Non-experimental quantitative designs",
  qualitative: "Qualitative designs",
  mixed: "Mixed methods designs",
  timing: "Designs by timing",
  purpose: "Designs by purpose",
};

/** How far a design can support claims about cause and effect. */
export type Causality = "strong" | "moderate" | "weak" | "none" | "either";

/** Traits the decision assistant compares with the researcher's answers. "either" matches any answer. */
export interface DesignTraits {
  causality: Causality;
  manipulation: "yes" | "no" | "either";
  timing: "once" | "repeated" | "either";
  emphasis: "quantitative" | "qualitative" | "mixed" | "either";
  cases: "single" | "multiple" | "either";
  setting: "natural" | "controlled" | "either";
}

/** Which research onion choices typically accompany a design (strong) or can (possible). */
export type OnionFit = Partial<Record<LayerId, { typical: readonly string[]; possible?: readonly string[] }>>;

/**
 * What the design expects of the project's variables:
 * - iv-dv: an independent variable to manipulate or compare, and a dependent variable to measure.
 * - measured: two or more measured variables.
 * - concepts: concepts to explore rather than variables to measure.
 * - both-kinds: measured variables and qualitative data.
 * - any: no particular expectation.
 */
export type VariableNeed = "iv-dv" | "measured" | "concepts" | "both-kinds" | "any";

/** Whether hypotheses usually accompany the design. */
export type HypothesisUse = "typical" | "possible" | "unusual";

export interface ResearchDesign {
  id: DesignId;
  name: string;
  family: DesignFamily;
  definition: string;
  purpose: string;
  whenUsed: string;
  strengths: readonly string[];
  limitations: readonly string[];
  typicalData: readonly string[];
  analysisMethods: readonly string[];
  examples: readonly string[];
  /** What the design takes for granted, which the researcher should be able to defend. */
  assumptions: readonly string[];
  typicalSample: string;
  timeRequirement: string;
  resourceRequirement: string;
  commonUse: string;
  traits: DesignTraits;
  onion: OnionFit;
  variables: VariableNeed;
  hypotheses: HypothesisUse;
  /** Words in objectives that suggest this design's purpose. */
  objectiveCues: RegExp;
  /** Reference ids, empty until academic review. */
  references: readonly string[];
}

const QUANT_ONION: OnionFit = {
  philosophy: { typical: ["positivism"], possible: ["realism", "pragmatism"] },
  approach: { typical: ["deductive"], possible: ["abductive"] },
  choice: { typical: ["quantitative"], possible: ["mixed-methods", "multi-method"] },
};
const QUAL_ONION: OnionFit = {
  philosophy: { typical: ["interpretivism"], possible: ["pragmatism", "realism"] },
  approach: { typical: ["inductive"], possible: ["abductive"] },
  choice: { typical: ["qualitative"], possible: ["multi-method", "mixed-methods"] },
};
const MIXED_ONION: OnionFit = {
  philosophy: { typical: ["pragmatism"], possible: ["realism"] },
  approach: { typical: ["abductive"], possible: ["deductive", "inductive"] },
  choice: { typical: ["mixed-methods"] },
};
const EITHER_TIME = { typical: ["cross-sectional", "longitudinal"] };
const EXPERIMENT_TRAITS: DesignTraits = { causality: "strong", manipulation: "yes", timing: "either", emphasis: "quantitative", cases: "multiple", setting: "controlled" };
const EXPERIMENT_CUES = /\b(test\w*|effects?|impacts?|caus\w*|interventions?|compar\w*|evaluat\w*)\b/i;
const QUAL_TRAITS: DesignTraits = { causality: "none", manipulation: "no", timing: "either", emphasis: "qualitative", cases: "multiple", setting: "natural" };
const MIXED_TRAITS: DesignTraits = { causality: "either", manipulation: "either", timing: "either", emphasis: "mixed", cases: "multiple", setting: "either" };

export const RESEARCH_DESIGNS: readonly ResearchDesign[] = [
  {
    id: "experimental",
    name: "Experimental",
    family: "experimental",
    definition: "The researcher changes one or more independent variables and measures the effect on a dependent variable, while controlling other influences.",
    purpose: "To establish cause and effect.",
    whenUsed: "When the question is whether something causes a change, and the cause can be manipulated ethically and practically.",
    strengths: ["The strongest general basis for claims about cause and effect.", "Clear, repeatable procedures."],
    limitations: ["Controlled conditions may not reflect real life.", "Many causes can't ethically or practically be manipulated."],
    typicalData: ["Measurements of the outcome before and after the intervention", "Records of which condition each participant received"],
    analysisMethods: ["Comparisons of group means", "Analysis of variance and regression"],
    examples: ["Comparing test scores of students taught with two revision methods."],
    assumptions: ["The independent variable can be manipulated.", "Other influences on the outcome can be controlled or balanced between groups."],
    typicalSample: "Participants allocated to two or more conditions; size set by a power calculation.",
    timeRequirement: "Moderate: planning, running the conditions and measuring the outcome.",
    resourceRequirement: "Moderate to high: materials for each condition and controlled settings.",
    commonUse: "Psychology, education, health and behavioural sciences.",
    traits: EXPERIMENT_TRAITS,
    onion: { ...QUANT_ONION, strategy: { typical: ["experiment"] }, timeHorizon: EITHER_TIME },
    variables: "iv-dv",
    hypotheses: "typical",
    objectiveCues: EXPERIMENT_CUES,
    references: [],
  },
  {
    id: "true-experimental",
    name: "True experimental",
    family: "experimental",
    definition: "An experiment in which participants are randomly assigned to conditions, usually including a control group, such as a randomised controlled trial.",
    purpose: "To establish cause and effect with the strongest protection against other explanations.",
    whenUsed: "When random assignment is possible and ethical.",
    strengths: ["Random assignment balances known and unknown influences between groups.", "Supports the strongest causal conclusions of any design."],
    limitations: ["Random assignment is often impossible or unethical in real settings.", "Participants may behave differently because they know they are in a study."],
    typicalData: ["Pre-test and post-test measurements", "Outcome measurements for treatment and control groups"],
    analysisMethods: ["Comparisons of treatment and control groups", "Analysis of covariance"],
    examples: ["A randomised trial of a new reading programme against usual teaching."],
    assumptions: ["Participants can be randomly assigned to conditions.", "The control group receives no version of the intervention."],
    typicalSample: "Participants randomly assigned to treatment and control groups; size set by a power calculation.",
    timeRequirement: "Moderate to high, especially with follow-up measurements.",
    resourceRequirement: "High: recruitment, randomisation and delivery of each condition.",
    commonUse: "Medicine, psychology, education and policy evaluation.",
    traits: EXPERIMENT_TRAITS,
    onion: { ...QUANT_ONION, strategy: { typical: ["experiment"] }, timeHorizon: EITHER_TIME },
    variables: "iv-dv",
    hypotheses: "typical",
    objectiveCues: EXPERIMENT_CUES,
    references: [],
  },
  {
    id: "quasi-experimental",
    name: "Quasi-experimental",
    family: "experimental",
    definition: "An intervention study without random assignment, usually comparing groups that already exist, such as classes or wards.",
    purpose: "To estimate the effect of an intervention where random assignment isn't possible.",
    whenUsed: "When groups are already formed, or random assignment would be impractical or unethical.",
    strengths: ["Works in real settings with existing groups.", "Often more practical and ethical than a true experiment."],
    limitations: ["Groups may differ in ways other than the intervention.", "Causal conclusions are weaker than with random assignment."],
    typicalData: ["Outcome measurements for intervention and comparison groups", "Measurements before the intervention, to compare the groups' starting points"],
    analysisMethods: ["Comparisons adjusted for starting differences", "Regression with control variables"],
    examples: ["Comparing two schools, one of which adopts a new timetable."],
    assumptions: ["The comparison group is similar enough to the intervention group.", "Differences between the groups can be measured and adjusted for."],
    typicalSample: "Existing groups, such as classes, wards or organisations.",
    timeRequirement: "Moderate: often follows an intervention over a term or longer.",
    resourceRequirement: "Moderate: access to comparable groups and repeated measurement.",
    commonUse: "Education, health services, social policy and management.",
    traits: { ...EXPERIMENT_TRAITS, causality: "moderate", setting: "either" },
    onion: { ...QUANT_ONION, strategy: { typical: ["experiment"], possible: ["case-study"] }, timeHorizon: EITHER_TIME },
    variables: "iv-dv",
    hypotheses: "typical",
    objectiveCues: EXPERIMENT_CUES,
    references: [],
  },
  {
    id: "pre-experimental",
    name: "Pre-experimental",
    family: "experimental",
    definition: "An intervention study with little or no control over other explanations, such as a single group measured before and after an intervention.",
    purpose: "To take a first look at whether an intervention may have an effect.",
    whenUsed: "In pilot studies, or when no comparison group is available.",
    strengths: ["Simple and quick to carry out.", "Useful for piloting an intervention or instrument."],
    limitations: ["Without a comparison group, other explanations for a change can't be ruled out.", "Rarely supports causal conclusions on its own."],
    typicalData: ["Measurements before and after the intervention for one group"],
    analysisMethods: ["Before-and-after comparisons", "Descriptive statistics"],
    examples: ["Measuring staff confidence before and after a single training day."],
    assumptions: ["Nothing other than the intervention changed the outcome in the meantime."],
    typicalSample: "A single group, often small.",
    timeRequirement: "Low to moderate.",
    resourceRequirement: "Low.",
    commonUse: "Pilot studies and service evaluations.",
    traits: { ...EXPERIMENT_TRAITS, causality: "weak", setting: "either" },
    onion: { ...QUANT_ONION, strategy: { typical: ["experiment"], possible: ["action-research"] }, timeHorizon: EITHER_TIME },
    variables: "iv-dv",
    hypotheses: "possible",
    objectiveCues: EXPERIMENT_CUES,
    references: [],
  },
  {
    id: "survey",
    name: "Survey",
    family: "non-experimental",
    definition: "Standardised questions asked of a sample of people, to describe a population or examine relationships between variables.",
    purpose: "To describe characteristics, attitudes or behaviours, and how they are related, across a population.",
    whenUsed: "When information is needed from many people, and the questions can be standardised.",
    strengths: ["Reaches many people efficiently.", "Standardised answers can be compared and analysed statistically."],
    limitations: ["Answers are limited to the questions asked.", "Relies on what people report, which may differ from what they do."],
    typicalData: ["Questionnaire responses", "Structured interview answers"],
    analysisMethods: ["Descriptive statistics", "Cross-tabulation, correlation and regression"],
    examples: ["A questionnaire on study habits sent to all first-year students."],
    assumptions: ["Respondents understand the questions as intended.", "The sample represents the population the findings are about."],
    typicalSample: "Often large; ideally a probability sample of the population.",
    timeRequirement: "Moderate: designing, piloting, distributing and analysing a questionnaire.",
    resourceRequirement: "Low to moderate, especially online.",
    commonUse: "Social sciences, business, health and education.",
    traits: { causality: "none", manipulation: "no", timing: "either", emphasis: "quantitative", cases: "multiple", setting: "natural" },
    onion: { ...QUANT_ONION, approach: { typical: ["deductive"], possible: ["inductive", "abductive"] }, strategy: { typical: ["survey"] }, timeHorizon: { typical: ["cross-sectional"], possible: ["longitudinal"] } },
    variables: "measured",
    hypotheses: "possible",
    objectiveCues: /\b(describ\w*|measur\w*|assess\w*|prevalence|levels?|attitudes?|views|relationships?)\b/i,
    references: [],
  },
  {
    id: "case-study",
    name: "Case study",
    family: "qualitative",
    definition: "An in-depth study of one or a few cases, such as an organisation, event or community, in their real-life context, often using several sources of evidence.",
    purpose: "To understand a complex situation in detail, where context matters.",
    whenUsed: "When “how” and “why” questions are asked about a contemporary situation the researcher can't control.",
    strengths: ["Rich understanding of how things work in practice.", "Can combine several kinds of evidence."],
    limitations: ["Findings from a few cases can't be generalised statistically.", "Defining the boundaries of the case can be difficult."],
    typicalData: ["Interviews", "Documents, observation and records"],
    analysisMethods: ["Thematic analysis", "Pattern matching and explanation building"],
    examples: ["How one hospital introduced electronic patient records."],
    assumptions: ["The case is worth studying in its own right, or illuminates a wider issue.", "The case's boundaries can be defined."],
    typicalSample: "One case, or a few cases chosen for a reason.",
    timeRequirement: "Moderate to high, depending on the depth of fieldwork.",
    resourceRequirement: "Moderate: access to the case and several sources of evidence.",
    commonUse: "Management, education, health, policy and social sciences.",
    traits: { causality: "none", manipulation: "no", timing: "either", emphasis: "either", cases: "single", setting: "natural" },
    onion: {
      philosophy: { typical: ["interpretivism", "realism"], possible: ["positivism", "pragmatism"] },
      approach: { typical: ["inductive", "abductive"], possible: ["deductive"] },
      choice: { typical: ["qualitative", "mixed-methods"], possible: ["quantitative", "multi-method"] },
      strategy: { typical: ["case-study"] },
      timeHorizon: EITHER_TIME,
    },
    variables: "any",
    hypotheses: "possible",
    objectiveCues: /\b(how|why|understand\w*|explor\w*|in depth|case)\b/i,
    references: [],
  },
  {
    id: "phenomenology",
    name: "Phenomenology",
    family: "qualitative",
    definition: "A study of how people experience a particular phenomenon, describing what that lived experience is like from their perspective.",
    purpose: "To understand the essence or meaning of an experience.",
    whenUsed: "When the question is about what an experience is like for the people who have it.",
    strengths: ["Detailed insight into lived experience.", "Centres participants' own perspectives."],
    limitations: ["Relies on small, carefully chosen samples.", "Requires careful handling of the researcher's own assumptions."],
    typicalData: ["In-depth interviews", "Written accounts of experience"],
    analysisMethods: ["Interpretative phenomenological analysis", "Thematic analysis of meaning"],
    examples: ["What returning to study after a long break is like for mature students."],
    assumptions: ["Participants can put their experience into words.", "Shared features of the experience can be identified across accounts."],
    typicalSample: "A small group of people who have all had the experience.",
    timeRequirement: "Moderate: interviews and detailed analysis.",
    resourceRequirement: "Low to moderate.",
    commonUse: "Health, nursing, psychology and education.",
    traits: QUAL_TRAITS,
    onion: { ...QUAL_ONION, strategy: { typical: ["phenomenology"] }, timeHorizon: { typical: ["cross-sectional"], possible: ["longitudinal"] } },
    variables: "concepts",
    hypotheses: "unusual",
    objectiveCues: /\b(experienc\w*|lived|meanings?|perceptions?)\b/i,
    references: [],
  },
  {
    id: "grounded-theory",
    name: "Grounded theory",
    family: "qualitative",
    definition: "A study that develops a theory from the data itself, collecting and analysing data at the same time until new data add little.",
    purpose: "To build a new explanation of a process where existing theory is limited.",
    whenUsed: "When little theory exists about a process, or existing theory doesn't fit the setting.",
    strengths: ["Theory closely grounded in evidence.", "Systematic procedures for analysis."],
    limitations: ["Time-consuming, because data collection and analysis alternate.", "Different versions follow different procedures, so the version must be named."],
    typicalData: ["Interviews", "Observation and documents"],
    analysisMethods: ["Coding and constant comparison", "Theoretical sampling to saturation"],
    examples: ["Developing a theory of how new managers learn their role."],
    assumptions: ["A theory can be developed from the data rather than tested against it.", "Sampling can continue until new data add little."],
    typicalSample: "Participants chosen as the emerging theory requires, until saturation.",
    timeRequirement: "High: collection and analysis alternate over time.",
    resourceRequirement: "Moderate.",
    commonUse: "Sociology, nursing, management and education.",
    traits: QUAL_TRAITS,
    onion: { ...QUAL_ONION, strategy: { typical: ["grounded-theory"] }, timeHorizon: EITHER_TIME },
    variables: "concepts",
    hypotheses: "unusual",
    objectiveCues: /\b(theor\w*|process\w*|develop\w*|explain\w*|how)\b/i,
    references: [],
  },
  {
    id: "ethnography",
    name: "Ethnography",
    family: "qualitative",
    definition: "A study of the culture and everyday life of a group, through an extended period spent with them.",
    purpose: "To understand a group's shared practices and meanings from the inside.",
    whenUsed: "When the question is about a group's culture, and long-term access to the group is possible.",
    strengths: ["Deep, first-hand understanding of everyday life.", "Shows what people do, not only what they say."],
    limitations: ["Very time-consuming.", "The researcher's presence may change how people behave."],
    typicalData: ["Participant observation and field notes", "Informal interviews and documents"],
    analysisMethods: ["Thematic and interpretive analysis of field notes", "Thick description"],
    examples: ["A year with a community sports club, studying belonging."],
    assumptions: ["The researcher can gain and keep access to the group.", "Extended immersion reveals practices that short visits miss."],
    typicalSample: "One group or setting, studied in depth.",
    timeRequirement: "High: months of fieldwork.",
    resourceRequirement: "Moderate to high: sustained time in the field.",
    commonUse: "Anthropology, sociology, education and organisation studies.",
    traits: { ...QUAL_TRAITS, timing: "repeated", cases: "single" },
    onion: { ...QUAL_ONION, strategy: { typical: ["ethnography"] }, timeHorizon: { typical: ["longitudinal"], possible: ["cross-sectional"] } },
    variables: "concepts",
    hypotheses: "unusual",
    objectiveCues: /\b(cultur\w*|practices?|everyday|communit\w*|group)\b/i,
    references: [],
  },
  {
    id: "narrative-inquiry",
    name: "Narrative inquiry",
    family: "qualitative",
    definition: "A study of people's experiences through the stories they tell, paying attention to how events are ordered and given meaning.",
    purpose: "To understand how people make sense of events over the course of their lives.",
    whenUsed: "When experience unfolds over time and is best understood through personal stories.",
    strengths: ["Keeps the richness and order of personal experience.", "Gives participants a voice."],
    limitations: ["Usually involves few participants.", "Stories are shaped by memory and by the way they are told."],
    typicalData: ["Life-story interviews", "Diaries, letters and other personal documents"],
    analysisMethods: ["Narrative analysis", "Thematic analysis across stories"],
    examples: ["The career stories of women in engineering."],
    assumptions: ["Participants' stories give access to how they understand their experience."],
    typicalSample: "A small number of participants, often studied in depth.",
    timeRequirement: "Moderate to high.",
    resourceRequirement: "Low to moderate.",
    commonUse: "Education, health, psychology and social work.",
    traits: QUAL_TRAITS,
    onion: { ...QUAL_ONION, strategy: { typical: ["narrative-inquiry"] }, timeHorizon: EITHER_TIME },
    variables: "concepts",
    hypotheses: "unusual",
    objectiveCues: /\b(stor\w*|narrativ\w*|lives|life|journeys?|careers?)\b/i,
    references: [],
  },
  {
    id: "action-research",
    name: "Action research",
    family: "qualitative",
    definition: "Researchers and participants work together to improve a practical situation through repeated cycles of planning, acting, observing and reflecting.",
    purpose: "To solve a real problem while generating knowledge about it.",
    whenUsed: "When the researcher is part of, or works closely with, the setting they want to improve.",
    strengths: ["Produces practical change as well as knowledge.", "Involves the people affected."],
    limitations: ["Findings are closely tied to one setting.", "The researcher's involvement makes objectivity harder to claim."],
    typicalData: ["Reflective journals and meeting notes", "Interviews, focus groups and before-and-after measures"],
    analysisMethods: ["Reflective and thematic analysis", "Simple comparisons across cycles"],
    examples: ["Teachers improving feedback practices over a school year."],
    assumptions: ["Participants are willing to take part in change.", "Each cycle can be evaluated before the next begins."],
    typicalSample: "The people in one setting, such as a team or a class.",
    timeRequirement: "High: several cycles of action and reflection.",
    resourceRequirement: "Moderate: sustained involvement from participants.",
    commonUse: "Education, nursing, social work and organisational development.",
    traits: { causality: "none", manipulation: "either", timing: "repeated", emphasis: "either", cases: "single", setting: "natural" },
    onion: {
      philosophy: { typical: ["pragmatism"], possible: ["interpretivism", "realism"] },
      approach: { typical: ["abductive"], possible: ["inductive", "deductive"] },
      choice: { typical: ["mixed-methods", "qualitative"], possible: ["multi-method", "quantitative"] },
      strategy: { typical: ["action-research"] },
      timeHorizon: { typical: ["longitudinal"] },
    },
    variables: "any",
    hypotheses: "possible",
    objectiveCues: /\b(improv\w*|chang\w*|develop\w*|practice|implement\w*)\b/i,
    references: [],
  },
  {
    id: "historical",
    name: "Historical",
    family: "qualitative",
    definition: "A study of past events, people or ideas using records and documents from, or about, the period.",
    purpose: "To understand what happened in the past, how and why.",
    whenUsed: "When the question is about the past, or about how a present situation developed.",
    strengths: ["Gives access to periods that can't be observed directly.", "The data aren't affected by the researcher's presence."],
    limitations: ["Records may be incomplete, biased or lost.", "Interpretation depends on understanding why the records were made."],
    typicalData: ["Archival documents and official records", "Letters, diaries, newspapers and oral histories"],
    analysisMethods: ["Source criticism", "Documentary and thematic analysis"],
    examples: ["Tracing how a national curriculum changed between 1988 and 2014."],
    assumptions: ["Enough records survive to answer the question.", "The records can be judged for reliability."],
    typicalSample: "The records that survive, selected for relevance.",
    timeRequirement: "Moderate to high, depending on access to archives.",
    resourceRequirement: "Low to moderate; archive visits may be needed.",
    commonUse: "History, education, policy and organisation studies.",
    traits: { causality: "none", manipulation: "no", timing: "either", emphasis: "either", cases: "either", setting: "natural" },
    onion: {
      philosophy: { typical: ["interpretivism", "realism"], possible: ["positivism", "pragmatism"] },
      approach: { typical: ["inductive", "abductive"], possible: ["deductive"] },
      choice: { typical: ["qualitative"], possible: ["quantitative", "mixed-methods", "multi-method"] },
      strategy: { typical: ["archival-research"] },
      timeHorizon: { typical: ["longitudinal"], possible: ["cross-sectional"] },
    },
    variables: "any",
    hypotheses: "unusual",
    objectiveCues: /\b(histor\w*|past|trac\w*|origins?|since|between \d{4})\b/i,
    references: [],
  },
  {
    id: "correlational",
    name: "Correlational",
    family: "non-experimental",
    definition: "A study that measures two or more variables as they occur, without manipulating them, to see whether and how strongly they are related.",
    purpose: "To identify and describe relationships between variables.",
    whenUsed: "When variables can't or shouldn't be manipulated, but their relationship matters.",
    strengths: ["Studies variables that can't be manipulated.", "Shows the strength and direction of relationships."],
    limitations: ["A relationship doesn't show cause and effect.", "A third variable may explain the relationship."],
    typicalData: ["Measurements of each variable for the same participants"],
    analysisMethods: ["Correlation", "Regression"],
    examples: ["Examining whether working hours are related to burnout among nurses."],
    assumptions: ["Each variable can be measured reliably.", "The sample shows enough variation in each variable."],
    typicalSample: "Enough participants to estimate relationships reliably; size set by a power calculation.",
    timeRequirement: "Low to moderate.",
    resourceRequirement: "Low to moderate.",
    commonUse: "Psychology, education, health and business.",
    traits: { causality: "none", manipulation: "no", timing: "either", emphasis: "quantitative", cases: "multiple", setting: "natural" },
    onion: { ...QUANT_ONION, strategy: { typical: ["survey"], possible: ["archival-research"] }, timeHorizon: EITHER_TIME },
    variables: "measured",
    hypotheses: "typical",
    objectiveCues: /\b(relationships?|relat\w*|associat\w*|correlat\w*|predict\w*)\b/i,
    references: [],
  },
  {
    id: "cross-sectional",
    name: "Cross-sectional",
    family: "timing",
    definition: "Data are collected at one point in time, giving a snapshot of a population or situation.",
    purpose: "To describe a situation, or compare groups, at one moment.",
    whenUsed: "When time is limited, or change over time isn't the question.",
    strengths: ["Quicker and cheaper than following people over time.", "Allows comparisons between groups at one moment."],
    limitations: ["Can't show change over time.", "Makes cause and effect hard to establish, because everything is measured at once."],
    typicalData: ["A single round of questionnaires, interviews or measurements"],
    analysisMethods: ["Descriptive statistics and group comparisons", "Correlation and regression"],
    examples: ["A survey of student wellbeing in one semester."],
    assumptions: ["A single moment is representative enough to answer the question."],
    typicalSample: "Any size; depends on the strategy it is combined with.",
    timeRequirement: "Low: one round of data collection.",
    resourceRequirement: "Low to moderate.",
    commonUse: "Across the social and health sciences, often combined with a survey.",
    traits: { causality: "none", manipulation: "no", timing: "once", emphasis: "either", cases: "multiple", setting: "natural" },
    onion: {
      philosophy: { typical: ["positivism", "interpretivism", "pragmatism", "realism"] },
      approach: { typical: ["deductive", "inductive", "abductive"] },
      choice: { typical: ["quantitative", "qualitative", "mixed-methods", "multi-method"] },
      strategy: { typical: ["survey", "case-study", "phenomenology"], possible: ["experiment", "grounded-theory", "narrative-inquiry", "archival-research"] },
      timeHorizon: { typical: ["cross-sectional"] },
    },
    variables: "any",
    hypotheses: "possible",
    objectiveCues: /\b(current\w*|at present|snapshot|compar\w*|describ\w*)\b/i,
    references: [],
  },
  {
    id: "longitudinal",
    name: "Longitudinal",
    family: "timing",
    definition: "Data are collected from the same people, groups or organisations at several points in time.",
    purpose: "To study change and development over time.",
    whenUsed: "When the question is about change, development or the order in which things happen.",
    strengths: ["Shows how things change over time.", "Gives stronger evidence about the order in which things happen."],
    limitations: ["Time-consuming and costly.", "Participants may drop out between rounds."],
    typicalData: ["Repeated questionnaires, measurements or interviews", "Existing records over time"],
    analysisMethods: ["Analysis of change over time", "Repeated-measures and growth models"],
    examples: ["Following graduates' careers over five years."],
    assumptions: ["Participants can be followed and will stay in the study.", "Measures stay comparable between rounds."],
    typicalSample: "A group followed over time, recruited larger to allow for dropout.",
    timeRequirement: "High: several rounds over months or years.",
    resourceRequirement: "High: keeping in touch with participants and repeating measurement.",
    commonUse: "Education, health, developmental psychology and labour studies.",
    traits: { causality: "weak", manipulation: "no", timing: "repeated", emphasis: "either", cases: "multiple", setting: "natural" },
    onion: {
      philosophy: { typical: ["positivism", "interpretivism", "pragmatism", "realism"] },
      approach: { typical: ["deductive", "inductive", "abductive"] },
      choice: { typical: ["quantitative", "qualitative", "mixed-methods", "multi-method"] },
      strategy: { typical: ["ethnography", "action-research", "archival-research"], possible: ["experiment", "survey", "case-study", "grounded-theory", "narrative-inquiry", "phenomenology"] },
      timeHorizon: { typical: ["longitudinal"] },
    },
    variables: "any",
    hypotheses: "possible",
    objectiveCues: /\b(over time|chang\w*|trends?|develop\w*|follow\w*|trajector\w*)\b/i,
    references: [],
  },
  {
    id: "descriptive",
    name: "Descriptive",
    family: "purpose",
    definition: "A study that sets out to describe what something is like: how common, how much, or what its characteristics are.",
    purpose: "To give an accurate picture of a situation, population or phenomenon.",
    whenUsed: "When little is documented about a situation, or a baseline is needed before further research.",
    strengths: ["Provides a clear, factual picture.", "A useful basis for later explanatory research."],
    limitations: ["Says what is happening, not why.", "Its value depends on accurate measurement and a representative sample."],
    typicalData: ["Questionnaires, observation or existing records"],
    analysisMethods: ["Frequencies, percentages and averages", "Descriptive summaries of qualitative data"],
    examples: ["Describing how often patients miss follow-up appointments."],
    assumptions: ["The features described can be measured or observed accurately."],
    typicalSample: "Chosen to represent the population described.",
    timeRequirement: "Low to moderate.",
    resourceRequirement: "Low to moderate.",
    commonUse: "Across disciplines, often as a first study.",
    traits: { causality: "none", manipulation: "no", timing: "either", emphasis: "either", cases: "either", setting: "natural" },
    onion: {
      philosophy: { typical: ["positivism", "interpretivism", "pragmatism", "realism"] },
      approach: { typical: ["deductive", "inductive", "abductive"] },
      choice: { typical: ["quantitative", "qualitative", "mixed-methods", "multi-method"] },
      strategy: { typical: ["survey", "case-study", "archival-research"], possible: ["ethnography", "action-research"] },
      timeHorizon: EITHER_TIME,
    },
    variables: "any",
    hypotheses: "unusual",
    objectiveCues: /\b(describ\w*|document\w*|profil\w*|prevalence|levels?|characteristics)\b/i,
    references: [],
  },
  {
    id: "explanatory",
    name: "Explanatory",
    family: "purpose",
    definition: "A study that sets out to explain why something happens, or how variables influence each other.",
    purpose: "To identify causes, mechanisms or reasons.",
    whenUsed: "When a pattern is known and the question is why it occurs.",
    strengths: ["Goes beyond description to explanation.", "Can test or develop theory."],
    limitations: ["Explanations need a design that can support them.", "Other explanations must be ruled out."],
    typicalData: ["Measured variables, or detailed qualitative accounts of processes"],
    analysisMethods: ["Regression and modelling", "Explanation building from qualitative data"],
    examples: ["Explaining why some students leave university in their first year."],
    assumptions: ["The pattern to be explained has already been established."],
    typicalSample: "Depends on the strategy it is combined with.",
    timeRequirement: "Moderate.",
    resourceRequirement: "Moderate.",
    commonUse: "Across disciplines, often following descriptive research.",
    traits: { causality: "either", manipulation: "either", timing: "either", emphasis: "either", cases: "either", setting: "either" },
    onion: {
      philosophy: { typical: ["positivism", "realism", "pragmatism"], possible: ["interpretivism"] },
      approach: { typical: ["deductive", "abductive"], possible: ["inductive"] },
      choice: { typical: ["quantitative", "mixed-methods"], possible: ["qualitative", "multi-method"] },
      strategy: { typical: ["experiment", "survey", "case-study"], possible: ["grounded-theory", "archival-research"] },
      timeHorizon: EITHER_TIME,
    },
    variables: "measured",
    hypotheses: "typical",
    objectiveCues: /\b(explain\w*|why|caus\w*|effects?|impacts?|influenc\w*|mechanisms?)\b/i,
    references: [],
  },
  {
    id: "exploratory",
    name: "Exploratory",
    family: "purpose",
    definition: "A study that explores a topic where little is known, to understand it better and identify questions for further research.",
    purpose: "To gain initial understanding and generate ideas or hypotheses.",
    whenUsed: "When a topic is new, poorly understood, or hasn't been studied in this setting.",
    strengths: ["Flexible and open to the unexpected.", "Identifies what later research should examine."],
    limitations: ["Findings are tentative.", "Rarely supports firm conclusions or generalisation."],
    typicalData: ["Interviews, focus groups and observation", "Documents and early pilot data"],
    analysisMethods: ["Thematic analysis", "Descriptive summaries"],
    examples: ["Exploring how small businesses used social media during a crisis."],
    assumptions: ["The topic isn't yet understood well enough for testing."],
    typicalSample: "Small and chosen for insight.",
    timeRequirement: "Low to moderate.",
    resourceRequirement: "Low to moderate.",
    commonUse: "Across disciplines, especially for new topics.",
    traits: { causality: "none", manipulation: "no", timing: "either", emphasis: "either", cases: "either", setting: "natural" },
    onion: {
      philosophy: { typical: ["interpretivism", "pragmatism"], possible: ["realism", "positivism"] },
      approach: { typical: ["inductive", "abductive"], possible: ["deductive"] },
      choice: { typical: ["qualitative", "mixed-methods"], possible: ["quantitative", "multi-method"] },
      strategy: { typical: ["case-study", "grounded-theory", "ethnography", "phenomenology"], possible: ["survey", "narrative-inquiry", "action-research"] },
      timeHorizon: EITHER_TIME,
    },
    variables: "concepts",
    hypotheses: "unusual",
    objectiveCues: /\b(explor\w*|understand\w*|identif\w*|insights?|investigat\w*)\b/i,
    references: [],
  },
  {
    id: "sequential-mixed",
    name: "Sequential mixed methods",
    family: "mixed",
    definition:
      "Quantitative and qualitative data are collected in separate phases, one after the other, so the first phase informs the second. For example, a survey followed by interviews that explain its results.",
    purpose: "To use one kind of data to explain, or build on, the other.",
    whenUsed: "When one phase's results are needed to design or interpret the next.",
    strengths: ["Each phase can be designed with the other's results in mind.", "Clear structure that is easy to report."],
    limitations: ["Takes longer, because the phases can't overlap.", "Participants may need to take part twice."],
    typicalData: ["Questionnaire data and interviews, collected in turn"],
    analysisMethods: ["Separate analysis of each phase", "Integration of findings in the interpretation"],
    examples: ["A survey of staff wellbeing, followed by interviews with staff whose scores were very high or very low."],
    assumptions: ["The first phase produces results that can shape the second.", "There is time for two phases."],
    typicalSample: "A larger sample for the quantitative phase, and a smaller selected sample for the qualitative phase.",
    timeRequirement: "High: two phases in turn.",
    resourceRequirement: "Moderate to high: skills in both kinds of research.",
    commonUse: "Health, education, social sciences and evaluation.",
    traits: { ...MIXED_TRAITS, timing: "repeated" },
    onion: { ...MIXED_ONION, strategy: { typical: ["survey", "case-study", "action-research"], possible: ["experiment"] }, timeHorizon: EITHER_TIME },
    variables: "both-kinds",
    hypotheses: "possible",
    objectiveCues: /\b(explain\w*|follow\w*|build\w*|then|phases?)\b/i,
    references: [],
  },
  {
    id: "concurrent-mixed",
    name: "Concurrent mixed methods",
    family: "mixed",
    definition:
      "Quantitative and qualitative data are collected in the same phase, analysed separately and then compared or merged. Also called a convergent design.",
    purpose: "To compare two kinds of evidence on the same question and see whether they agree.",
    whenUsed: "When both kinds of data are needed and can be collected together.",
    strengths: ["Takes less time than collecting data in two phases.", "Two kinds of evidence can confirm or challenge each other."],
    limitations: ["Needs a plan for when the two kinds of results disagree.", "Merging different kinds of data takes skill."],
    typicalData: ["Questionnaire data and interviews, collected at the same time"],
    analysisMethods: ["Separate analysis of each strand", "Side-by-side comparison or joint displays"],
    examples: ["A questionnaire and interviews with patients on the same ward in the same month."],
    assumptions: ["Both kinds of data address the same question.", "The two strands can be compared meaningfully."],
    typicalSample: "The same or overlapping participants for both strands.",
    timeRequirement: "Moderate.",
    resourceRequirement: "Moderate to high: skills in both kinds of research.",
    commonUse: "Health, education, social sciences and evaluation.",
    traits: { ...MIXED_TRAITS, timing: "once" },
    onion: { ...MIXED_ONION, strategy: { typical: ["survey", "case-study"], possible: ["action-research", "experiment"] }, timeHorizon: { typical: ["cross-sectional"], possible: ["longitudinal"] } },
    variables: "both-kinds",
    hypotheses: "possible",
    objectiveCues: /\b(compar\w*|converg\w*|both|and how|triangulat\w*)\b/i,
    references: [],
  },
  {
    id: "embedded-mixed",
    name: "Embedded mixed methods",
    family: "mixed",
    definition:
      "One kind of data plays a supporting role within a larger study of the other kind, such as interviews inside an experiment to understand how participants experienced the intervention.",
    purpose: "To answer a secondary question that the main design can't answer on its own.",
    whenUsed: "When a main design, often an experiment, needs a smaller strand of another kind of data.",
    strengths: ["Adds understanding without a second full study.", "Fits within an existing design."],
    limitations: ["The supporting strand can be too small to stand on its own.", "The two strands' purposes must be kept clear."],
    typicalData: ["The main study's data, plus a smaller strand of the other kind"],
    analysisMethods: ["The main design's analysis, with the supporting strand analysed to inform it"],
    examples: ["Interviewing some participants in a trial about how they experienced the intervention."],
    assumptions: ["The main design is appropriate for the main question.", "The supporting strand answers a distinct, secondary question."],
    typicalSample: "The main study's sample, with a subgroup for the supporting strand.",
    timeRequirement: "Moderate to high, depending on the main design.",
    resourceRequirement: "Moderate to high.",
    commonUse: "Health trials, evaluation and education.",
    traits: MIXED_TRAITS,
    onion: { ...MIXED_ONION, strategy: { typical: ["experiment", "case-study"], possible: ["survey", "action-research"] }, timeHorizon: EITHER_TIME },
    variables: "both-kinds",
    hypotheses: "possible",
    objectiveCues: /\b(experienc\w*|within|alongside|process\w*|implement\w*)\b/i,
    references: [],
  },
];

export function getDesign(id: DesignId): ResearchDesign {
  const design = RESEARCH_DESIGNS.find((candidate) => candidate.id === id);
  if (!design) throw new RangeError(`Unknown research design: ${id}`);
  return design;
}

export const isDesignId = (id: string): id is DesignId => (DESIGN_IDS as readonly string[]).includes(id);
