export { COMPARED_LAYERS, LAYERS, OPTIONS, findOption, getLayer, optionsFor } from "./research-onion";
export { allJudgements, areCompared, judge, judgementsFor, validateSelection } from "./compatibility";
export { GENERAL_JUSTIFICATION, summarise, type OnionSummary } from "./recommendation";
export { REFERENCES, doiUrl, getReference, referenceMarkdown, referenceRuns, referenceText } from "./references";
export { ALTERNATIVE_VIEWS, EVIDENCE, GENERAL_VIEW, alternativeViewFor, evidenceFor } from "./evidence";
export { explainJudgement, explainOption, type JudgementExplanation, type OptionExplanation } from "./explanation";
export { EVIDENCE_DESCRIPTIONS, EVIDENCE_LABELS, FIT_LABELS, SUMMARY_LABELS, SUMMARY_TEXT } from "./labels";
export { escapeHtml, toMarkdown, toPlainText, toPrintHtml } from "./export";
export {
  LAYER_ORDER,
  type AlternativeView,
  type Evidence,
  type EvidenceLevel,
  type Fit,
  type FitRule,
  type Judgement,
  type LayerId,
  type OnionLayer,
  type OnionOption,
  type OnionSelection,
  type Reference,
} from "./types";
export {
  METHODOLOGIES,
  PROJECT_FIELDS,
  PROJECT_FIELD_LABELS,
  createProjectDraft,
  describeProject,
  filledFields,
  parseList,
  updateProjectDraft,
  type MethodologyId,
  type ProjectField,
  type ResearchProjectChanges,
  type ResearchProjectDraft,
} from "./research-project";
export {
  QUESTION_TYPES,
  QUESTION_TYPE_IDS,
  detectApproach,
  detectQuestionTypes,
  getQuestionType,
  type QuestionDimension,
  type QuestionType,
  type QuestionTypeId,
  type TypeDetection,
} from "./question-types";
export {
  ELEMENT_LABELS,
  ELEMENT_STATUS_LABELS,
  QUESTION_ELEMENT_IDS,
  identifyElements,
  type ElementFinding,
  type ElementStatus,
  type QuestionElementId,
} from "./question-elements";
export { PLACEHOLDERS, buildDraftQuestion, contextPhrase, suggestQuestionTypes, type DraftQuestion, type TypeSuggestion } from "./question-builder";
export {
  FINER_CRITERIA,
  FINER_JUDGEMENT_LABELS,
  evaluateFiner,
  type FinerAssessment,
  type FinerCriterion,
  type FinerJudgement,
} from "./finer";
export {
  CONSISTENCY_LABELS,
  GENERAL_NOTE_SOURCES,
  QUESTION_BUILDER_LIMITATIONS,
  checkConsistency,
  evaluateQuestion,
  type AcademicNote,
  type ConsistencyNote,
  type Feedback,
  type QuestionEvaluation,
} from "./question-evaluator";
export {
  DIRECTIONS,
  HYPOTHESIS_FORMS,
  HYPOTHESIS_REVIEW_NOTE,
  HYPOTHESIS_ROLES,
  HYPOTHESIS_TYPES,
  HYPOTHESIS_TYPE_IDS,
  RELATIONSHIP_KINDS,
  getHypothesisType,
  typesOf,
  type Direction,
  type HypothesisForm,
  type HypothesisRelationship,
  type HypothesisRole,
  type HypothesisType,
  type HypothesisTypeId,
  type ProjectHypothesis,
  type RelationshipKind,
} from "./hypothesis-types";
export { DIRECTION_LABELS, describeDirection, readDirection, type DirectionReading } from "./hypothesis-direction";
export { checkNullAlternative, statesAbsence, type PairIssue } from "./hypothesis-null";
export {
  HYPOTHESIS_PLACEHOLDERS,
  generateHypotheses,
  validateOptions,
  type HypothesisDraft,
  type HypothesisOptions,
  type HypothesisPair,
  type HypothesisPlaceholder,
  type HypothesisSet,
} from "./hypothesis-builder";
export {
  CHECK_IDS,
  CHECK_LABELS,
  CHECK_STATUSES,
  CHECK_STATUS_LABELS,
  type CheckId,
  type CheckStatus,
  type HypothesisCheck,
  type PairTexts,
} from "./hypothesis-checks";
export { checkAlignment, methodologyGuidance, pairVariables, type MethodologyNote } from "./hypothesis-alignment";
export { validateHypothesisPair } from "./hypothesis-validator";
export {
  HYPOTHESIS_BUILDER_LIMITATIONS,
  HYPOTHESIS_REVIEW_ITEMS,
  applyHypotheses,
  evaluateHypotheses,
  hypothesesText,
  pairLabel,
  relationshipRows,
  textsFor,
  toProjectHypotheses,
  type HypothesisEdits,
  type HypothesisEvaluation,
  type PairEvaluation,
} from "./hypothesis-summary";
export {
  EMPTY_FRAMEWORK,
  RELATIONSHIP_TYPES,
  RELATIONSHIP_TYPE_INFO,
  VARIABLE_TYPES,
  VARIABLE_TYPE_LABELS,
  type ConceptualFramework,
  type ConnectorStyle,
  type FrameworkRelationship,
  type FrameworkVariable,
  type Point,
  type RelationshipType,
  type VariableType,
} from "./conceptual-types";
export {
  FORM_RELATIONSHIP,
  FRAMEWORK_LIMITATIONS,
  FRAMEWORK_REVIEW_ITEMS,
  NUDGE_STEP,
  NUDGE_STEP_LARGE,
  addRelationship,
  addVariable,
  applyFramework,
  autoLayout,
  changeVariableType,
  defaultShortLabel,
  deleteRelationship,
  deleteVariable,
  frameworkFromProject,
  moveVariable,
  nudgeVariable,
  renameVariable,
  resetLayout,
  setDescription,
  setRelationshipLabel,
  setRelationshipType,
  setShortLabel,
  supportingObjectives,
  traceRelationship,
  type NewRelationship,
  type NewVariable,
  type RelationshipTrace,
} from "./conceptual-framework";
export {
  LAYOUT,
  layoutFramework,
  measureText,
  LABEL_POSITION,
  segmentCrossesBox,
  segmentsOverlap,
  wrapText,
  type Crossing,
  type EdgeLabel,
  type EdgePath,
  type FrameworkLayout,
  type GroupBox,
  type LayoutOptions,
  type NodeBox,
  type Overlap,
} from "./conceptual-layout";
export { describeFramework, describeRelationship, describeVariable } from "./conceptual-description";
export {
  WARNING_CODES,
  findDuplicates,
  findLoops,
  validateFramework,
  type FrameworkWarning,
  type WarningCode,
} from "./conceptual-validation";
export {
  EXPORT_COLOURS,
  EXPORT_FONT,
  PNG_DPI,
  PNG_SCALE,
  PX_TO_PT,
  crc32,
  escapeXml,
  pdfString,
  pngChunk,
  pngSize,
  setPngDpi,
  textBaselines,
  toPdf,
  toSvg,
  type ExportOptions,
} from "./conceptual-export";
export {
  MEASUREMENT_LEVELS,
  MEASUREMENT_LEVEL_INFO,
  VARIABLE_KINDS,
  VARIABLE_KIND_INFO,
  VARIABLE_PLACEHOLDERS,
  levelFit,
  type LevelFit,
  type MeasurementFamily,
  type MeasurementLevel,
  type MeasurementLevelInfo,
  type ProjectVariable,
  type VariableIndicator,
  type VariableKind,
  type VariableKindInfo,
  type VariableSource,
} from "./variable-types";
export {
  addIndicator,
  addVariable as addProjectVariable,
  changeVariableKind,
  createVariable,
  deleteIndicator,
  deleteVariable as deleteProjectVariable,
  duplicateVariable,
  moveIndicator,
  renameVariable as renameProjectVariable,
  updateIndicator,
  updateVariable,
  type IndicatorDetails,
  type VariableDetails,
} from "./variable-builder";
export { FRAMEWORK_KIND, hypothesisKinds, importVariables, mergeImported } from "./variables";
export { connectionsFor, describeSource, originOf, originSummary, type VariableConnections } from "./variable-relationships";
export {
  VARIABLE_CHECK_IDS,
  VARIABLE_CHECK_LABELS,
  validateSet,
  validateVariable,
  type SetCheck,
  type VariableCheck,
  type VariableCheckId,
} from "./variable-validator";
export {
  TABLE_HEADINGS,
  VARIABLE_LIMITATIONS,
  VARIABLE_REVIEW_ITEMS,
  applyVariables,
  draftItems,
  operationalisation,
  variableRows,
  variablesTable,
  type OperationalisationStep,
  type VariableRow,
} from "./variable-summary";
export {
  DESIGN_FAMILY_LABELS,
  DESIGN_IDS,
  RESEARCH_DESIGNS,
  getDesign,
  isDesignId,
  type Causality,
  type DesignFamily,
  type DesignId,
  type DesignTraits,
  type ResearchDesign,
} from "./design-types";
export {
  DECISION_QUESTIONS,
  DECISION_UNSURE,
  consistentDesigns,
  narrowDesigns,
  validateAnswers,
  type AnswerFit,
  type DecisionAnswers,
  type DecisionQuestionId,
  type DesignNarrowing,
} from "./design-decision";
export {
  EMPTY_DESIGN,
  answerQuestion,
  chooseDesign,
  cleanDesignRecord,
  removeDesign,
  setDesignNotes,
  setJustification,
  shortlistDesign,
  type ResearchDesignRecord,
} from "./research-design";
export {
  judgeOnionLayer,
  projectVariables,
  type OnionJudgement,
  type OnionSubject,
} from "./design-compatibility";
export {
  COMPATIBILITY_CHECK_IDS,
  COMPATIBILITY_LABELS,
  QUESTION_DESIGNS,
  checkCompatibility,
  supportingElements,
  type CompatibilityCheck,
  type CompatibilityCheckId,
  type CompatibilityStatus,
} from "./design-compatibility";
export { DESIGN_CHECK_IDS, DESIGN_CHECK_LABELS, SHORT_JUSTIFICATION_WORDS, validateDesign, type DesignCheck, type DesignCheckId } from "./design-validator";
export {
  COMPARISON_ASPECTS,
  DESIGN_LIMITATIONS,
  DESIGN_REVIEW_ITEMS,
  applyDesign,
  compareDesigns,
  comparisonTable,
  type Comparison,
  type ComparisonRow,
} from "./design-summary";
export {
  SAMPLING_CATEGORY_LABELS,
  SAMPLING_TECHNIQUES,
  SAMPLING_TECHNIQUE_IDS,
  getTechnique,
  isTechniqueId,
  type SamplingCategory,
  type SamplingTechnique,
  type SamplingTechniqueId,
  type SamplingTraits,
} from "./sampling-types";
export {
  SAMPLING_ANSWER_LABELS,
  SAMPLING_QUESTIONS,
  consistentTechniques,
  narrowTechniques,
  validateSamplingAnswers,
  type SamplingAnswer,
  type SamplingAnswers,
  type SamplingFit,
  type SamplingQuestionId,
  type TechniqueNarrowing,
} from "./sampling-decision";
export {
  EMPTY_POPULATION,
  EMPTY_SAMPLING_PLAN,
  POPULATION_LABELS,
  answerSamplingQuestion,
  chooseTechnique,
  cleanSamplingPlan,
  parseResponseRate,
  removeTechnique,
  setPlanText,
  setResponseRate,
  shortlistTechnique,
  updatePopulation,
  type PlanText,
  type PopulationDefinition,
  type SamplingPlan,
} from "./sampling";
export {
  SAMPLING_CHECK_IDS,
  SAMPLING_CHECK_LABELS,
  checkSamplingCompatibility,
  samplingSupport,
  type SamplingCheck,
  type SamplingCheckId,
} from "./sampling-compatibility";
export { PLAN_CHECK_IDS, PLAN_CHECK_LABELS, SHORT_REASON_WORDS, validateSamplingPlan, type PlanCheck, type PlanCheckId } from "./sampling-validator";
export {
  SAMPLING_ASPECTS,
  SAMPLING_LIMITATIONS,
  SAMPLING_REVIEW_ITEMS,
  applySampling,
  compareTechniques,
  samplingComparisonTable,
  samplingPlanText,
  type SamplingComparison,
} from "./sampling-summary";
export {
  CONFIDENCE_LEVELS,
  DEFAULT_INPUTS,
  INPUT_INFO,
  SAMPLE_SIZE_METHODS,
  SAMPLE_SIZE_METHOD_IDS,
  getSampleSizeMethod,
  type ConfidenceLevel,
  type InputId,
  type InputInfo,
  type SampleSizeInputs,
  type SampleSizeMethod,
  type SampleSizeMethodId,
} from "./sample-size-types";
export { cochran, finitePopulationCorrection, krejcieMorgan, roundDown, roundNearest, roundUp, yamane, zScore } from "./sample-size-formulas";
export {
  DEFAULT_SAMPLE_SIZE_PLAN,
  assertCalculable,
  calculateSampleSize,
  chooseMethod,
  cleanSampleSizePlan,
  formatNumber,
  parseNumber,
  setSampleSizeText,
  updateInputs,
  type CalculationStep,
  type SampleSizePlan,
  type SampleSizeResult,
} from "./sample-size";
export { checkInputs, checkSampleSizeCompatibility, inputProblems, type InputProblem, type SampleSizeCheck } from "./sample-size-validator";
export { assumptionsFor, suggestedInputs, type Assumption } from "./sample-size-assumptions";
export {
  SAMPLE_SIZE_LIMITATIONS,
  SAMPLE_SIZE_REVIEW_ITEMS,
  SCENARIO_GROUPS,
  applySampleSize,
  sampleSizeReport,
  sensitivity,
  type Scenario,
} from "./sample-size-summary";
export {
  MEASURING_SECTIONS,
  QUESTIONNAIRE_PLACEHOLDERS,
  QUESTION_TYPES as QUESTIONNAIRE_ITEM_TYPES,
  QUESTION_TYPE_INFO,
  SECTION_KINDS,
  SECTION_KIND_INFO,
  TYPE_FOR_LEVEL,
  type AnswerForm,
  type Question,
  type Questionnaire,
  type QuestionnaireSection,
  type QuestionType as QuestionnaireItemType,
  type QuestionTypeInfo,
  type SectionKind,
  type SectionKindInfo,
} from "./questionnaire-types";
export {
  SCALE_PRESETS,
  SCALE_PRESET_IDS,
  createScale,
  displayLabels,
  scaleCoding,
  scaleProblems,
  scaleSignature,
  scoreFor,
  setReverseScored,
  setScaleAnchors,
  setScaleDirection,
  setScaleLabels,
  setScaleStart,
  type QuestionScale,
  type ScalePreset,
  type ScalePresetId,
} from "./questionnaire-scales";
export {
  EMPTY_QUESTIONNAIRE,
  answerOptions,
  cleanQuestionnaire,
  findQuestion,
  findSection,
  insertionIndex,
  matrixRows,
  orderedQuestions,
  questionNumbers,
  questionWording,
  rowLetter,
  sectionQuestions,
  type Wording,
} from "./questionnaire";
export { DEFAULT_SECTIONS, addSection, moveSection, removeSection, renameSection, sectionText, setQuestionnaireTitle, setSectionContent } from "./questionnaire-sections";
export {
  addQuestion,
  changeSection,
  changeType,
  createQuestion,
  defaultScaleFor,
  deleteQuestion,
  duplicateQuestion,
  linkQuestion,
  moveQuestion,
  nextQuestionId,
  setQuestionScale,
  updateQuestion,
  type NewQuestion,
  type QuestionDetails,
} from "./questionnaire-items";
export {
  SECTION_FOR_KIND,
  addMissingQuestions,
  buildQuestionnaire,
  questionOrigin,
  questionnaireVariables,
  sectionGuidance,
  suggestedType,
  unmeasured,
  type OriginStep,
  type QuestionOrigin,
} from "./questionnaire-builder";
export { checkQuestionnaire, type QuestionnaireCheck } from "./questionnaire-validator";
export {
  EMPTY_SECTION_NOTE,
  PAGE_BREAK_TEXT,
  QUESTIONNAIRE_LIMITATIONS,
  QUESTIONNAIRE_REVIEW_ITEMS,
  REQUIRED_NOTE,
  applyQuestionnaire,
  questionLine,
  questionnaireCounts,
  questionnaireDocument,
  questionnaireMarkdown,
  questionnaireText,
  type Answer,
  type DocumentBlock,
  type QuestionnaireCounts,
} from "./questionnaire-summary";
export { PDF_PAGE, layoutPdf, pageLabel, questionnaireDocx, questionnairePdf, utf8, xmlText, zip, type PdfItem, type PdfPage, type ZipEntry } from "./questionnaire-export";
export {
  ANALYSIS_FAMILY_LABELS,
  ANALYSIS_METHODS,
  ANALYSIS_METHOD_IDS,
  NON_PARAMETRIC_ALTERNATIVE,
  RECOMMENDATION_STRENGTHS,
  STRENGTH_LABELS,
  getAnalysisMethod,
  type AnalysisFamily,
  type AnalysisMethod,
  type AnalysisMethodId,
  type RecommendationStrength,
} from "./data-analysis-types";
export { MEASURES, MEASURE_FOR_LEVEL, MEASURE_LABELS, analysisProfile, measureVariable, type AnalysisProfile, type Measure, type MeasuredVariable, type MethodologicalChoice } from "./data-analysis-profile";
export { applyContext, controlRules, manovaRule, mediationRules, mergeRecommendations, moderationRules, multipleRules, pairRules, recommend, stronger, twoGroups, weaken, withFallbacks, type Recommendation } from "./data-analysis-rules";
export {
  STAGE_IDS,
  STAGE_TITLES,
  allRecommendations,
  analysisQuestions,
  describeStage,
  measuresStage,
  modelStage,
  overview as analysisOverview,
  questionRecommendations,
  questionsStage,
  recommendAnalyses,
  uses as planUses,
  type AnalysisPlan,
  type AnalysisQuestion,
  type AnalysisStage,
  type StageId,
} from "./data-analysis";
export { DATA_ANALYSIS_LIMITATIONS, DATA_ANALYSIS_REVIEW_ITEMS, analysisPlanText } from "./data-analysis-summary";
export { parseVariableLines, variablesFromLines, type VariableLine } from "./variable-lines";
